mbeddr/mbeddr.core

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.expressions/languageModels/behavior.mps
Hi,
post increment should give a++; previously it was ++a;  So I added a  render readable method in com.mbeddr.core.expressions.behavior.PostIncrementExpression_behaviour
Please review and merge the same.
> Post Increment render readable method 

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.expressions/languageModels/behavior.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.udt/languageModels/behavior.mps
Added render readable for Int2Enum
Modified render readable for EnumtoInt and Int2Boolean to standard format
> Added/Modified renderReadable for Int2Enum, Enum2Int and Int2Boolean

- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/models/test/analyses/concurrency/checks/testcode/access.mps
- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/models/test/analyses/concurrency/checks/testcode/consumer.mps
- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/models/test/analyses/concurrency/checks/testcode/memory_sep.mps
- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/models/test/analyses/concurrency/checks/testcode/tests@tests.mps
- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/models/test/analyses/concurrency/checks/testcode/various.mps
- code/languages/com.mbeddr.analyses/solutions/test.analyses.concurrency.checks.testcode/test.analyses.concurrency.checks.testcode.msd
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/assert_seq.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/assert_seq@tests.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/assert_seq_scope.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/atomicVar.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/datarace_free.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/happens_after.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/passert.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/synchronise.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/models/test/analysis/cbmc/concurrency/testcode/weakMemory.mps
- code/languages/com.mbeddr.analyses/solutions/test.analysis.cbmc.concurrency.testcode/test.analysis.cbmc.concurrency.testcode.msd
> missing files

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/generator/template/main@generator.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/languageModels/typesystem.mps
Hi,
This commit includes comparison of two structures using AssertEquals.
Regards,
Swathi
> assert equals for structType

- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/com.mbeddr.doc.aspect.mpl
- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
Hi ,
As I have said earlier in the pull request 1296, I just wrote an enhancement in the doc.aspect.ui.plugin such that it looks for document aspect in the extending languages also without causing any performance issue.
Please review the same.
Note: Unknowingly I gave pull request to master. Please ignore 1309.
Regards,
Dinesh
> documentation changes pull request to milestone/v-1.5-3

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.print.pluginSolution/models/com/mbeddr/mpsutil/print/pluginSolution/plugin.mps
Changed the action print editor from View menu to File menu
> Changed the location of print editor action to file menu

- code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.concurrency/com.mbeddr.ext.components.concurrency.mpl
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.concurrency/languageAccessories/com/mbeddr/ext/components/concurrency/util.mps
- code/languages/com.mbeddr.ext/tests/test.ex.ext.components.concurrency/models/test/ex/ext/components/concurrency/externalSchedule/compositecomponent/plainC.mps
Hi,
tasks refered from instances lying several levels deeper inside the composite component is referred properly now.
Please review and accept the request.
Please ensure no tests are broken.
I didnt run unit tests,
Regards, 
Dinesh
> concurrency language fixes

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/generator/template/main@generator.mps
- code/languages/com.mbeddr.core/tests/test.ex.core/test/ex/core/gswitchBlockExpr.mps
> fix expression source generator

- code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/run.mps
Hi,
Due to few problems in the cbmc 5.5, changing the supported versions check to look for  cbmc version higher than 5.1.
please review and merge in milestone/v15-3
Regards,
Dinesh
> Supporting all cbmc higher than 5.1

- code/plugins/sl-all/mps-hacks/solutions/de.slisson.mps.hacks.editor/models/de/slisson/mps/hacks/editor.mps
- code/plugins/sl-all/mps-tables/languages/de.slisson.mps.tables/runtime/models/de/slisson/mps/tables/runtime/cells.mps
This changes contain fixes for completion of table cells affecting https://youtrack.jetbrains.com/issue/MPS-25165
The problem would be fixed with this change together with using MPS build 162.2263 or higher
> fix completion of table cells

- code/languages/com.mbeddr.debugger/languages/com.mbeddr.core.debug/languageModels/debugger.mps
- code/languages/com.mbeddr.debugger/languages/com.mbeddr.core.debug/languageModels/plugin.mps
Extension point DebugSessionListener, created for debugger suspend event. With this you can write extension and register them to perform certain task when debugger get suspended.
> New extension point DebugSessionListener, created for debugger suspend event

- code/languages/com.mbeddr.debugger/languages/com.mbeddr.core.debug/languageModels/debugger.mps
Modified code for adding proper breakpoints details for desired c file and line number in the DSL while debugging.
> Modified code for adding proper breakpoints details for desired c file and line number in the DSL while debugging.

- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.statemachines/languageModels/editor.mps
Hi,
To differentiate the composite state with normal state in state machine graphical, I have changed the border size of the composite state. Please review the changes and merge to milestone.
Regards,
> Differentiating composite state and normal state in Graphical view - State machine

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.contextactions.runtime/models/com/mbeddr/mpsutil/contextactions/runtime/plugin.mps
Changed the label name Context actions (mbeddr) to context actions
> Changed the label name - context actions

- code/languages/com.mbeddr.debugger/languages/com.mbeddr.core.debug/languageModels/debugger.mps
Removed the system console print statement which is slowing the debugging process as it is getting executed for each filtering of DSL stackframe.
> Removed system console print statement to fasten up debugging

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/languageAccessories/com/mbeddr/core/unittest/messages.mps
Hi,
I have added an extra method in UnitTestMessages for displaying the actual values in double type.
Please review the changes and merge into milestone/v16-2
Regards,
> Support for actual value to be shown as Double type in the ranges.

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.grammarcells/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.grammarcells/models/com/mbeddr/mpsutil/grammarcells/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.grammarcells.runtime/models/com/mbeddr/mpsutil/grammarcells/runtime.mps
The value written to/read from the model is inverted if this is
configured in the inspector of the FlagCell.
> GrammarCells: FlagCell can be inverted

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
Added runtime dependencies to the platform plugins to get rid of the error messages in the build script. 
We can't merge it at the moment because of a upstream [bug](https://youtrack.jetbrains.com/issue/MPS-27141) in MPS.
> WIP: build: fix runtime plugin dependencies

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.blutil/languageModels/dataFlow.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.conceptswitch/models/test.ts.conceptswitch@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.conceptswitch/test.ts.conceptswitch.msd
MPS will no longer report the error when conceptswitch contains return
statement in a branch.
Add a test case for this particular problem.
> Fix 'unreachable code' error when using conceptswitch

- code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/run.mps
- code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/ui.mps
Hi,
Just added a checkbox in the cprover preferences panel to enable the saving of results as html files.
Previously, the html results saving was controlled by a static variable which cannot be changed by the user.
Regards,
Dinesh
> Saving Analysis Results as HTML

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
The Updater does not update existing editors when the hints are changed
via `setInitialHint`. If there are hints to be set the updaters is now
triggered with a call to `update`.
> doc: update after pushing hints

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/languageModels/structure.mps
Currently `ForEachStatement` is not implementing `ILoopStatement` concept, which is implemented by other loops concepts hence to make it inline with other loop concepts making `ForEachStatement `to implement `ILoopStatement `concept.
> Added ForEachStatement to implement ILoopStatement to identify it as a loop

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/com.mbeddr.mpsutil.actionsfilter.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/constraints.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/intentions.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/com.mbeddr.mpsutil.actionsfilter.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
Now with the action filters language is also possible to configure the actions available in the toolbar.
Besides configuring the available actions it is also possible to customize icons.
> actionFilter: Implemented toobar customization

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram.sandbox/com.mbeddr.mpsutil.conceptdiagram.sandbox.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram.sandbox/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/com.mbeddr.mpsutil.conceptdiagram.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/structure.mps
Now the concept-diagram can display concepts defined in other languages.
> mpsutil: enhanced conceptdiagram with the possibility to add new languages in scope

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/languageModels/behavior.mps
changed data provider concept function return type to object to match the interface
> Fix data provider function return type

- code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.mock/languageModels/behavior.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.mock/languageModels/editor.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/components.mpl
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/behavior.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/constraints.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/editor.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/intentions.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/scripts.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/structure.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/typesystem.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.compositecomponents/languageModels/editor.mps
- Users get to know the concrete component concept of given instance, with no need to check the component definition
- New abstract concepts Instance and Connector for more general modeling
> Generalize the representations of components and component instances

- code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.mock/languageModels/behavior.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components.mock/languageModels/editor.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/components.mpl
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/behavior.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/constraints.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/editor.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/intentions.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/scripts.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/structure.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/typesystem.mps
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.compositecomponents/languageModels/editor.mps
- generalize component-related concepts
- rename concepts according to naming convention
> Cherry picks from the branch maintenance/mps20173

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.margincell.runtime/models/com/mbeddr/mpsutil/margincell/runtime.mps
@till-f 
(I don't have rights to push there yet)
> SECA-628 avoid ModelAccessError in MarginCellLayout

- code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/run.mps
- code/languages/com.mbeddr.analyses/tests/test.analyses.cbmc/models/test/analyses/cbmc/cbmc_arguments@tests.mps
- code/languages/com.mbeddr.analyses/tests/test.analyses.cbmc/models/test/analyses/cbmc/counterexample/mbeddr/components@tests.mps
- code/languages/com.mbeddr.analyses/tests/test.analyses.cbmc/models/test/analyses/cbmc/counterexample/mbeddr/statemachines@tests.mps
- code/languages/com.mbeddr.analyses/tests/test.analyses.cbmc/models/test/analyses/cbmc/robustness@tests.mps
Update the failed anaylses tests, according to the passed ones of master branch
> sync the analyses tests of mps20173 branch with the ones of master branch

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/languageAccessories/com/mbeddr/core/unittest/messages.mps
Hi All,
From the unit-test result message(Unittest_Helper), there are some chances(some outside simulation which uses TestResult.xml file might fail) that tests may not be completed. In those cases the result message in the console says "Tests execution finished successfully!". This is somewhat confusing to user since those tests were never complete. So I have removed Successfully from the print statement and formatted some statements.
Please review the changes and merge with milestone/v17.1-1
Kind Regards,
> Updated test result message and added some new lines stt

- code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
Add com.mbeddr.doc.pluginSolution to the build script in order to ensure that it is deployed.
> Include mbeddr.doc.pluginSolution in build

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.doc/.mps/modules.xml
- code/languages/com.mbeddr.doc/_spreferences/TypeSizeConfiguration/module.msd
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
- code/languages/com.mbeddr.doc/tests/tests.ts.doc/models/testBuildConfigPresence@tests.mps
- code/languages/com.mbeddr.doc/tests/tests.ts.doc/tests.ts.doc.msd
- fix for errors in generation when including documents
- fix for cleaning docGen folder
- fix for ModelContentRefWord html generation
> Bugfixes for doc language

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/com.mbeddr.mpsutil.interpreter.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/typesystem.mps
Added check to validate that an interpreter node is defined in a module of kind "other"
> mpsutil.interpreter: added checking rule to ensure usage in plugin

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/generator/template/main@generator.mps
Optimized switchStatement to if/else generation for the case where SwitchCases are empty or commented out
> Switch generator optimization

- code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.var.annotations/languageModels/intentions.mps
In the isApplicable method of the intention 'TogglePresenceCondition',the link attribute of the node is checked whether it is optional or not.But for the root nodes the link attribute will be null , hence while invoking the method isOptional(),null pointer exception pops up and hence no other intentions comes up for the root nodes when ALT+ENTER is pressed.
I have added a null check for for the attribute 'link' before invoking the method isOptional.
Please review the changes and kindly merge with milestone/v19.2_20183.
Regards ,
Vignesh M
> Null pointer exception during execution of isApplicable method for the intention 'TogglePresenceCondition'

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/constraints.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/typesystem.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
Evaluator bundles into one object several services needed to evaluate
expressions: an IContext, an ICoverageAnalyzer and a ComputationTrace.
These services are often passed together to various methods, putting
them all into one class simplifies method signatures.
> Introduce 'evaluator' expression and Evaluator class

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
Store evaluators in a hash(multi)map by concept.
> interpreter: speed up evaluator lookup

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules.gen/generator/template/main@generator.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.udt/languageModels/editor.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.udt/languageModels/structure.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.udt/languageModels/textGen.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.placeholderTextList/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.contextactions.runtime/models/com/mbeddr/mpsutil/contextactions/runtime.mps
This pull request contains 4 fixes that where required after migrating a customer project from mps 2018.1 -> 2019.3. Changes should not have implications for others but please review carefully.
> Fixes for "zb" customer project (from branch zb/19.3)

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide.execution.lang/com.mbeddr.mpsutil.editingGuide.execution.lang.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/com.mbeddr.mpsutil.editingGuide.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/models/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/models/constraints.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/models/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/models/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.execution/com.mbeddr.mpsutil.editingGuide.execution.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.execution/models/com/mbeddr/mpsutil/editingGuide/execution.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.plugin/com.mbeddr.mpsutil.editingGuide.plugin.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.sandbox/com.mbeddr.mpsutil.editingGuide.sandbox.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.sandbox/models/com/mbeddr/mpsutil/editingGuide/sandbox/demo.mps
editingGuide pulled in IVisibleElementProvider. This dependency is now replaced with a custom interface, INodeExporter.
> editingGuide: drop dependency on com.mbeddr.core

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.targetchooser/models/com/mbeddr/mpsutil/targetchooser.mps
The problem was that the tree is disposed with the dialog meaning that after the dialog is closed
you could no longer get the selected object.
To go around this we save the selected object in the ok action.
> mpsutil.targetchooser: target chooser always returns null

- code/languages/com.mbeddr.doc.aspect/.mps/vcs.xml
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
As it has some performance impact.
> Dont load contents of DocumentationProjectPlugin when tab is closed

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/com.mbeddr.mpsutil.projectview.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.projectview/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
A few cleanups in the CustomProjectView class and support for an optional toolbar to customize the view.
> Toolbar support for custom project view

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.xmodel.actions/models/plugin.mps
StorageType is no longer required.
> mpsutil.smodule: fixed generator

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps
An IllegalArgumentException was thrown if a toolbar action group id wasn't set.
> Optional toolbar action group id

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/behavior.mps
which was requested by the CPP implementation based on mbeddr at https://github.com/DSLFoundry/mbeddr.core/blob/mps-2020.1/documentation/cpp/migration-issues.md
> make some behavior methods virtual 

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.smodule.runtime/models/com/mbeddr/mpsutil/smodule/runtime/lib.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.smodule/models/test.com.mbeddr.mpsutil.smodule.operation@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.smodule/test.com.mbeddr.mpsutil.smodule.msd
Don't ignore the passed in storage type and provide binary compatible
methods for existing code.
> mpsutil.smodule: fix storage type detection

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageModels/plugin.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
- code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.transitiveIncludes.mps
This PR backports #2164 to MPS 2020.1 right now there are no plans to port it to 2020.2.
> backport multi doc include

- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
- code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/code.mps
See merged PR #2182 for a discussion on this change. This is the change for current master, i.e., 2021.1. The PR #2182 was the same change for 2020.3 maintenance.
> Show NodeAttributes in "embed model as image" paragraphs in mbeddr.doc

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
> Enhance control of 'allImports'-method (#2211)

- code/applications/com.mbeddr.build-examples/solutions/com.baselanguage.unless.build/build.xml
- code/applications/tutorial/solutions/com.mbeddr.tutorial.buildProject/build.xml
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.statements/languageModels/editor.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.statements/statements.mpl
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.serialization/com.mbeddr.ext.serialization.mpl
- code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.serialization/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.lantest/com.mbeddr.mpsutil.lantest.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.lantest/languageModels/editor.mps
The language was removed in mps-extensions.
> Remove de.itemis.mps.tooltips references

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.httpserver/models/com/mbeddr/mpsutil/httpserver/plugin.mps
Fixes the exception: java.net.BindException: Address already in use
> Stop http server regardless of isRunning status when stop is requested

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
Backport of #2216 for MPS 2021.1
> Tracer: Only set showInAnyCase flag if requested (backport: 2021.1)

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
Before this PR the flag was set internal to true even when the flag itself was false.
> Tracer: Only set showInAnyCase flag if requested

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_markdown/com.mbeddr.doc.gen_markdown.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_markdown/generator/templates/com.mbeddr.doc.gen_markdown.generator.templates@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageModels/structure.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.markdown/com.mbeddr.doc.markdown.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.markdown/models/com.mbeddr.doc.markdown.behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.markdown/models/com.mbeddr.doc.markdown.editor.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.markdown/models/com.mbeddr.doc.markdown.structure.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.markdown/models/com.mbeddr.doc.markdown.textGen.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/constraints.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
- code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.markdown.sandbox/models/com.mbeddr.doc.markdown.sandbox.doc2markdown.mps
- code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.markdown.sandbox/models/com.mbeddr.doc.markdown.sandbox.markdown.mps
Nested lists are now supported in the doc and markdown language as well as the html and markdown generator.
- TAB: increase the indentation
- SHIFT+TAB: decrease the indentation
> Documentation/Markdown language: support for nested lists

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.xmlImport/models/plugin.mps
The parse wasn't able to parse cdata sections correctly because the matcher was missing.
I also made some methods public api which allow easier usage outside of intelijs virtual files by providing a InputStream directly.
> mpsutil: allow parsing cdata sections

- build.gradle
- build/com.mbeddr/build.gradle
- build/com.mbeddr/distribution/build.gradle
- build/com.mbeddr/languages/build.gradle
- build/com.mbeddr/platform/build.gradle
- build/thirdparty/graphviz/build.gradle
❗❗ This PR should only be merged after write access to the old Nexus is deactivated.❗❗
In this PR we do:
- remove the publication to the old projects.itemis nexus
- remove the dependency to the old projects.itemis nexus
> removed usage of old nexus repository

- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/intentions.mps
- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/structure.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/models/com/mbeddr/doc/aspect/runtime.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
- make links clickable in the documentation aspect
- use the selected section as the title of the current documentation aspect tab
- focus the node that the tool scrolls to when opening the documentation
> Documentation aspect: small improvements

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.httpserver/models/com/mbeddr/mpsutil/httpserver/plugin.mps
The starting of the server didn't work for me because of using localhost as the host, so the server was always in a failing state. I've also removed the excessive restarting of the server. Now there shouldn't be an error message when reload classes. Ultimately, the language should be removed completely because there is already the built-in MPS sever, but currently we don't have a migration.
> Httpserver: improve starting and stopping logic

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
That way, tests can be referenced in the documentation.
> Generate documentation before tests

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.doc/.mps/modules.xml
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/com.mbeddr.doc.self.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/generator/template/com/mbeddr/doc/self/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/languageModels/com.mbeddr.doc.self.plugin.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
- code/languages/com.mbeddr.doc/languages/terms/com.mbeddr.doc.terms.mpl
- code/languages/com.mbeddr.doc/languages/terms/languageModels/behavior.mps
- code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.doc/models/main.mps
- code/languages/com.mbeddr.mpsutil/solutions/doc.com.mbeddr.mpsutil.multilingual/models/doc/com/mbeddr/mpsutil/multilingual/docs.mps
- fixes #2239
- fail the generation when an image can't be generated instead of silently failing
> Documentation: generate images in own facet

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.userstyles.runtime/models/com/mbeddr/mpsutil/userstyles/runtime/plugin.mps
Full error message:
```
Cannot create configurable
java.lang.NullPointerException: Parameter specified as non-null is null: method com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass, parameter pluginDescriptor
at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt)
at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:440)
at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:346)
at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:42)
at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:116)
at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.ja …
```
> Userstyles: Fix NullPointer: Cannot create configurable

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.datepicker.sandbox/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.datepicker/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.datepicker.runtime/models/com/mbeddr/mpsutil/datepicker/runtime/model.mps
> Fix entering dates into the datepicker

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/com.mbeddr.mpsutil.hyperlink.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/languageModels/plugin.mps
The language now survives reloading and also removes all listeners when it is unloaded.
> Hyperlink: fix loading and unloading of the language

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/com.mbeddr.mpsutil.filepicker.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/models/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/models/intentions.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.genericactions/models/com/mbeddr/mpsutil/genericactions/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.genreview/models/com.mbeddr.mpsutil.genreview.plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.postprocessGeneratedFiles.runtime/models/com/mbeddr/mpsutil/postprocessGeneratedFiles/runtime/rt.mps
I've also fixed a freeze in the filepicker language. This PR also fixes https://github.com/mbeddr/mbeddr.core/issues/2262.
> Don't throw exceptions when the output path doesn't exit

- CHANGELOG.md
- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/editor.mps
> doc.aspect: make DocumentedConceptAnnotation deletable

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.smodule.runtime/models/com/mbeddr/mpsutil/smodule/runtime/lib.mps
Original code used an AsyncPromise and waited for its result but in some cases it would deadlock. I suspect the problem is that the code to set the promise would throw an exception and never set a result nor an error. This PR rewrites the code to use runInUIThreadAndWait which is guaranteed to terminate one way or the other.
> ModelHelper#createModel(): prevent deadlock when called from EDT

- code/applications/IntegratedCExample/solutions/EmbeddedProgram/models/presentation.mps
- code/applications/com.mbeddr.build-examples/languages/com.baselanguage.unless/sandbox/com.baselanguage.unless.sandbox.msd
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.checks/com.mbeddr.core.checks.mpl
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
- code/languages/com.mbeddr.ext/tests/test.ex.ext.messaging/models/test/ex/ext/messaging/tests.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.ccmenu/com.mbeddr.mpsutil.ccmenu.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.ccmenu/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.contextactions.runtime/models/com/mbeddr/mpsutil/contextactions/runtime/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.jfreechart.runtime/models/com/mbeddr/mpsutil/jfreechart/runtime/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.plantuml/solutions/pluginSolution/models/com/mbeddr/mpsutil/plantuml/pluginSolution/plugin.mps
This PR addresses some internal changes that were required to fix bugs originating from the 2022.2 migration. 
Closes #2281
> Fix bugs left from migration to 2022.2

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.multilingual.common.runtime/com.mbeddr.mpsutil.multilingual.common.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.multilingual.common.runtime/models/com/mbeddr/mpsutil/multilingual/common/runtime/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.multilingual.settings.runtime/com.mbeddr.mpsutil.multilingual.settings.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.multilingual.settings.runtime/models/com/mbeddr/mpsutil/multilingual/settings/runtime/plugin.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.mpsutil.multilingual/models/test/ts/mpsutil/multilingual/baseLanguage@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.mpsutil.multilingual/models/test/ts/mpsutil/multilingual/common@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.mpsutil.multilingual/models/test/ts/mpsutil/multilingual/concept@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.mpsutil.multilingual/test.ts.mpsutil.multilingual.msd
The issues only appear in MPS 2022.3:
- https://youtrack.jetbrains.com/issue/MPS-35911 (explanation is in ticket)
- https://youtrack.jetbrains.com/issue/MPS-35979 (the initialization of tools changed in the IntelliJ platform)
> Fix initialization issues

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide.execution.lang/models/editor.mps
Alexei Quapp's commit 672025e5db39445aa6cbd00fcddd773b7b4efd22 from branch refactor/mt-mps20203-with-seca-193 somehow was missed to be merged into the maintenance branch.
Due to a layout-problem, the description-text was moved down below the hint and the buttons and thus overlapping with them.
Same goes for the hint text in some cases.
Introduced `TopDownLayoutCells` to resolve the overlaying of cells.
> EditingGuide: Fix layout-bug in the task description

- CHANGELOG.md
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps
The goal was to improve the visual separation of individual assessments in an assessment container.
Before:
After:
> Improve assessment editors

- code/applications/IntegratedCExample/solutions/EmbeddedProgram/models/presentation.mps
- code/applications/tutorial-dsls-extensions/solutions/mbeddr.tutorial.dsls.extensions.main/models/newLanguages.mps
- code/applications/tutorial-dsls-extensions/tests/mbeddr.tutorial.shonan.test/models/mbeddr/tutorial/shonan/test/diffusion@tests.mps
- code/applications/tutorial-dsls-extensions/tests/mbeddr.tutorial.shonan.test/models/mbeddr/tutorial/shonan/test/stencil_util@tests.mps
- code/applications/tutorial/solutions/mbeddr.tutorial.main/models/mbeddr/tutorial/main/defaultExtensions.mps
- code/applications/tutorial/solutions/mbeddr.tutorial.main/models/mbeddr/tutorial/main/req.mps
- code/languages/com.mbeddr.analyses/solutions/com.mbeddr.analyses.lantest.pluginSolution/models/com/mbeddr/analyses/lantest/pluginSolution/semantic_checker_statemachines.mps
- code/languages/com.mbeddr.analyses/tests/test.analyses.cbmc.testcode/models/_000_coverage.mps
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/languageModels/constraints.mps
- code/languages/com.mbeddr.core/tests/test.assessments/models/test.assessments@tests.mps
- code/languages/com.mbeddr.core/tests/test.assessments/test.assessments.msd
- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/sandbox/models/com/mbeddr/doc/aspect/exampleLanguage/sandbox.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.slides/generator/template/com/mbeddr/slides/generator/template/main@generator.mps
- code/languages/com.mbeddr.ext/tests/test.ex.ext.components/test/ex/ext/components/_generators_coverage.mps
- code/languages/com.mbeddr.ext/tests/test.ex.ext.messaging/models/test/ex/ext/messaging/tests.mps
- code/languages/com.mbeddr.ext/tests/test.ext.components.nodes_tracing/models/_assessment.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.incrementalcomputation.example/sandbox/models/de.itemis.mps.lazypropagation.example.sandbox.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.lantest.sandbox/models/com.mbeddr.mpsutil.lantest.demolang.sandbox.harness.mps
- code/languages/com.mbeddr.mpsutil/tests/test.ts.mpsutil.multilingual/models/test/ts/mpsutil/multilingual/concept@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/models/tests.com.mbeddr.mpsutil.json.tests@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/tests.com.mbeddr.mpsutil.json.msd
The grammar cells update in MPS-extensions has caused some breakage. This PR fixes the broken tests.
> Fix failing tests

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/intentions.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/com.mbeddr.mpsutil.traceExplorer.msd
I've backported the second commit because we also need it in 2022.2.
Fixes issue #2336
> Fix the documentation annotation adding order

- tools/BigProject/src/main/java/com/mbeddr/BigProjectGenerator.java
Include Eclipse.Debugger in the generated big project.
> BigProject: include Eclipse.Debugger

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.nodediff/com.mbeddr.mpsutil.nodediff.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.nodediff/models/com/mbeddr/mpsutil/nodediff/plugin.mps
This PR fixes https://github.com/mbeddr/mbeddr.core/issues/2303.
> Revert "Remove com.mbeddr.mpsutil.nodediff"

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/typesystem.mps
- code/languages/com.mbeddr.rcp/solutions/com.mbeddr.rcp.actions/models/com/mbeddr/rcp/actions/plugin.mps
The PR fixes https://github.com/mbeddr/mbeddr.core/issues/2205.
> mpsutil.actionsfilter: check if referenced actions are valid

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/com.mbeddr.mpsutil.interpreter.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/com.mbeddr.mpsutil.interpreter.dataFlow.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/languageModels/typesystem.mps
- fixes https://github.com/mbeddr/mbeddr.core/issues/2381
> mpsutil.interpreter:implement dataflow analysis

- CHANGELOG.md
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.codereview/com.mbeddr.core.codereview.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/com.mbeddr.doc.self.mpl
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/languageModels/editor.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.self/languageModels/structure.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
- code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.nodeaccess/com.mbeddr.mpsutil.nodeaccess.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.xmodel.actions/com.mbeddr.mpsutil.xmodel.actions.msd
> mbeddr.doc: Add support for rendering the inspector in ModelContentAsImageParagraph and SectionAsImageParagraph

- CHANGELOG.md
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.contextactions.runtime/models/com/mbeddr/mpsutil/contextactions/runtime/plugin.mps
I believe there is still an initialization issue with tools in MPS which we can't fix and is not easily reproducible at the moment.
At least the exceptions should be fixed.
> Fix initialization issues in the context actions and tool and catch null pointer in the documentation tool

- CHANGELOG.md
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/editor.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.statements/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.asynccell.sandbox/models/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.asynccell.sandbox/models/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editingGuide/models/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/com.mbeddr.mpsutil.editor.displayControl.sandbox.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/models/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink.sandbox/com.mbeddr.mpsutil.hyperlink.sandbox.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink.sandbox/models/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/languageAccessories/com/mbeddr/mpsutil/hyperlink/runtime.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/com.mbeddr.mpsutil.actionsfilter.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.asynccell/README.md
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.asynccell/models/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.execution/models/com/mbeddr/mpsutil/editingGuide/execution.mps
This PR integrates necessary changes for itemis SECURE which were implemented on #2221 and therefore by #2198 by others. I've cherrypicked and updated the necessary commits and ommited all unnecessary/ now irrelevant changes after reviewing all the commits.
❗ The only change where I'm unsure and would like some advice/ additional review is: 
`com.mbeddr.mpsutil.actionsfilter.runtime`: Set the solution kind to `NONE`. (`eee1745d`)
- `Force Save All` and `Execute Re-Runnable Migrations` on `com.mbeddr.core` and `com.mbeddr.mpsutil`
- `ProgramFragments` support error suppression, i.e. all model-checking errors are suppressed in `ProgramFragments`, so modelchecker will disregard them and not clutter.
- Fragment module depends on its original module, to access data that is needed, but in the …
> Integrate changes needed for SECURE

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com/mbeddr/mpsutil/common/util.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.common/models/test.com.mbeddr.mpsutil.common.util@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.common/test.com.mbeddr.mpsutil.common.msd
This PR contains the actual implementation `Traversal<T>` with a lot of javadoc documentation and many test cases. 
See the tests for examples how to use it. There are two different APIs which can be used:
- a compact API based on static methods and lambdas (used for simple traversals and searching for some specific node)
- a inheritance-based API with `@Override`, this can be used if additional data has to be stored and collect during the traversal
This solves #2435.
Here is an example of using the compact API from IETS3.Core:
> Provide utility class for breadth-first traversal and test suite

- CHANGELOG.md
- code/languages/com.mbeddr.analyses/solutions/com.mbeddr.analyses.sat4j/com.mbeddr.analyses.sat4j.msd
- code/languages/com.mbeddr.analyses/solutions/com.mbeddr.analyses.z3.lib/com.mbeddr.analyses.z3.lib.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.opencsv/com.opencsv.msd
- code/languages/com.mbeddr.mpsutil/solutions/org.apache.batik/org.apache.batik.msd
- code/languages/com.mbeddr.mpsutil/solutions/org.mockito/org.mockito.msd
- code/languages/com.mbeddr.mpsutil/solutions/org.xml/org.xml.msd
In the Java tab, contributes extensions to MPS was set to no.
> Fix classloading issues with some stubs

- build/com.mbeddr/languages/build.gradle
Useful for pull requests where we want to build everything to check.
> Add the ability to force platform build

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
> TraceExplorer: add interface for retrieving mapped nodes (#2468)

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
addresses issue: #2468
Adds the required read access
> TraceExplorer: fix missing read access for node mapper (#2468)

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
> TraceExplorer: weakens too restricted interface again (#2468)

- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
> TraceExplorer: Fixed NPE (#2468)

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
addresses issue: #2468 
**Breaking change**:
- the ITraceRecord interface was extended by a method
> TraceExplorer: Extended ITraceRecord interface and fixed method (#2468)

- tools/BigProject/.mps/libraries.xml
Changes were likely committed accidentally.
> Restore BigProject libraries.xml

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
> add callback function when trace node is add/inserted into the tree

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
- subprojects/com.mbeddr/platform/build.gradle
The build time of the language decreased from platform build time to 1 minute. You still have to restart MPS 3 times for it to see the new plugin after running `./gradlew install`.
> extract the actionsfilter language into a separate build script + show the currently loaded profile in the preferences

- build/com.mbeddr/distribution/build.gradle
- build/com.mbeddr/platform/build.gradle
- build/publishing/build.gradle
Make the [Publish GitHub](https://mps.builds.itemis.cloud/buildConfiguration/Mbeddr2_Mbeddr_Gradle_Release_PublishGithub) TeamCity build configuration work again for maintenance/mps20222.
Partially cherry-picked from maintenance/mps20223.
> Fix GitHub release

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
20% of the tests were not executed due to classloading issues.
> Migration 2024.1 cleanup

- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/com.mbeddr.doc.aspect.runtime.msd
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/models/com/mbeddr/doc/aspect/runtime.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/com.mbeddr.doc.aspect.ui.msd
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
Sometimes the language is not build and then the aspect can't be loaded.
> Surround LanguageRuntime#getAspect calls with try-catch statements

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram.sandbox/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/editor.mps
It made the layouting more compact but also worse.
> mpsutil.conceptdiagram: remove the custom node placement strategy

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.runconfiguration/solutions/pluginSolution/models/com/mbeddr/core/runconfiguration/pluginSolution/plugin.mps
StyleRegistry.getInstance will be removed in MPS 2025.1
> Don't use deprecated StyleRegistry singleton

- build.gradle
> Bump MPS version

- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/models/com/mbeddr/doc/aspect/runtime.mps
- code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps
Even if there is currently no documentation to show or some other issue, the tool should not be closed.
> doc.aspect.ui: don't close the documentation tool ever

- code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps
Please note that you have to use the "performance" hint to make it active. This editor will only work for simple cases.
> core.base: provide a simplified and better performing editor for ElementDocumentation

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
The changes to the search tool got lost in a merge from 2023.2 to 2024.1.
> Restore lost changes

- subprojects/com.mbeddr/build.gradle
- subprojects/com.mbeddr/platform/build.gradle
A few refactorings around the Gradle build and its use of configurations. See individual commits for details.
> Refactor Gradle build configurations

- subprojects/com.mbeddr/platform/build.gradle
fileValue wants a File but mpsHomeDir is a String.
> build: fix building with custom MPS

- code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.requirements/solutions/pluginSolution/models/com/mbeddr/cc/requirements/pluginSolution/plugin.mps
- code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.var.annotations/solutions/pluginSolution/models/com/mbeddr/cc/var/annotations/pluginSolution/plugin.mps
- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.print.pluginSolution/models/com/mbeddr/mpsutil/print/pluginSolution/plugin.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.review.runtime/models/com/mbeddr/mpsutil/review/runtime/plugin.mps
A few groups were still updating on the EDT thread.
> change the remaining action groups to update in the background

- code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
- fixes https://github.com/mbeddr/mbeddr.core/issues/2023
> core.base: add the search module action to the transient modules actions

- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/com.mbeddr.doc.aspect.mpl
- code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/typesystem.mps
- fixes https://github.com/mbeddr/mbeddr.core/issues/2175
> doc.aspect: add a quickfix to create a dummy reference to BaseConcept so that the aspect descriptor gets generated

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.ecoreimporter.testing/com.mbeddr.mpsutil.ecore.testing.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.ecoreimporter.testing/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.collections.runtime/com.mbeddr.mpsutil.collections.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.collections.runtime/models/com.mbeddr.mpsutil.collections.runtime.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.ecore.testing.runtime/com.mbeddr.mpsutil.ecore.testing.runtime.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.ecore.testing.runtime/models/com/mbeddr/mpsutil/ecore/testing/runtime/main.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.ecore.metaModelImport/test.com.mbeddr.mpsutil.ecore.metaModelImport.msd
- code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/models/tests.com.mbeddr.mpsutil.json.tests@tests.mps
- code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/tests.com.mbeddr.mpsutil.json.msd
- code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
- code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
missing migration was causing problem in downstream projects.
This PR ran remigrate only
> Re-apply migration

- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter.test/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/com.mbeddr.mpsutil.interpreter.mpl
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/generator/template/main@generator.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps
- code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
- fixes https://github.com/mbeddr/mbeddr.core/issues/1242
> mpsutil.interpreter: improve error messages

- build.gradle
- subprojects/com.mbeddr/build.gradle
- subprojects/com.mbeddr/distribution/build.gradle
- subprojects/com.mbeddr/languages/build.gradle
- subprojects/com.mbeddr/platform/build.gradle
- subprojects/publishing/build.gradle
- fixes https://github.com/mbeddr/mbeddr.core/issues/1622
> Add descriptions to all Gradle tasks

- CHANGELOG.md
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram.sandbox/languageModels/structure.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/structure.mps
No changes can be made to the structure of languages. The diagrams can still be layouted though.
> mpsutil.conceptdiagram: add an option to make the diagrams read-only

- code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
Fix for MPS-38286 revealed few missing dependencies in the build project, the patch adds these into com.mbeddr.platform build project
> MPS-38286 fix reported incomplete plugin dependencies

- CHANGELOG.md
- code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
- code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.requirements/languageModels/editor.mps
- code/languages/com.mbeddr.mpsutil/.mps/modules.xml
- code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.extensionclass/languageModels/behavior.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.strings/models/com.mbeddr.mpsutil.strings.util.mps
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.wizard.sandbox/com.mbeddr.mpsutil.wizard.sandbox.msd
- code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.wizard.sandbox/models/com/mbeddr/mpsutil/process/sandbox/plugin.mps
- code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.extensionclass.source/test.com.mbeddr.mpsutil.extensionclass.source.msd
- code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
* moved sandbox solution to correctly named folder
* renamed plugin to c.m.mpsutil.wizard
> fixed rename of the mpsutil.process

- .github/renovate.json5
Configuration option name has changed in the latest Renovate release.
> renovate: change baseBranches -> baseBranchPatterns
