code/languages/com.mbeddr.core/languages/com.mbeddr.core.arrays/languageModels/textGen.mps

null (NULL) can be explicitly (void*)0 instead of 0. Invisible with gcc, but makes cbmc on windows aware of null pointers and all (with flag --pointer-check).
Misra C 2004 Sec. 6.11 refers to NULL only as the "null pointer constant (the value 0 cast to type void*)". 
However, C11 Sec. 6.3.2.3 paragraph 3 says that "an integer constant expression with the value 0, or such an expression cast to type void *, is called a null pointer constant" -- thus also covering the 0 constant without cast.

Suggestions

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.udt/languageModels/behavior.mps
code/languages/com.mbeddr.core/tests/test.ex.core/test/ex/core/typedefsAndTypes.mps
code/languages/com.mbeddr.core/tests/test.ts.core/models/tests1@tests.mps

if a typedef referenced a type that is a referece to an other module content
this module content was not returned as a dependencie. Causing the typesystem
checks not being aware of this dependency.
fixes #1439

core: declare typedef dependencies correctly

---

code/plugins/sl-all/mps-richtext/languages/richtext/models/de/slisson/mps/richtext/runtime/selection.mps

Hi,
This pull request is part of the defect accent-2407.
When shift+up is done on any rich text , no such method exception is thrown on the constructor of RichTextSelection class file. In the SelectionInfoImpl.createSelection method, jetbrains is using reflection to get the constructor and create a new instance out of it. 
The CellInfo.class is part of j.m.o.editor.cells but the RichTextSelection has implemented a constructor having a different CellInfo.class which is part of j.m.nodeEditor.cells and it is deprecated. I have updated this reference. Please review and merge into milestone/v15-3
Regards,
Dinesh

NoSuchMethodException while selecting words from comment statement

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.expressions/languageModels/editor.mps

Hi,
The unsigned integer literal which was made abstract and deprecated by Sascha was reverted by me yesterday and as a result of that, multiple entries are being listed in the code completion menu if you type a number. For example, if you type "10", it was not automatically mapping it as number literal and it shows two entries as "10" in the code completion menu.
The unsigned integer literal was abstract previously, abstract concepts are not listed in the code completion by default. Since I reverted it and made non-abstract, it made itself available for the code completion.
This behaviour was easily found by a failing unit test in the accent repository.
So I have specified an editor for the unsigned integer literal and the problem of multiple entries in the code completion menu is not …

Restricting Multiple Entries (for Number Literal) in the code completion menu

---

code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/constraints.mps
code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.statemachines/languageModels/constraints.mps

Hi,
When you create a structure with few members and access those members inside a function, it is throwing node cast exception. The example and the errors are shown in the following snapshot.
Unable to cast from 
1. concept: com.mbeddr.core.udt.structure.StructType to concept: com.mbeddr.ext.statemachines.structure.StatemachineType
2. concept: com.mbeddr.core.udt.structure.StructType to concept: com.mbeddr.ext.components.structure.InterfaceType
I found that the stacktraces are taking me to the constraints of 1. SmVarTarget_Constraints 
2. InterfaceTypeDataRefTarget_Constraints
I could see an explicit casting is done there and so I have added isInstanceOf checks in those two places.Please review and merge in milestone/v15-3
Regards,
Dinesh

Node cast exception on accessing the structure members

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.httpserver/com.mbeddr.mpsutil.httpserver.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.httpserver/models/com/mbeddr/mpsutil/httpserver/plugin.mps

if the application is in unittest mode the http server now picks up the port
it uses from the env variable "MBEDDR_TEST_HTTP_PORT". If that variable is not
present or does not contain a valid port the property mbeddr.test.http.port is read
if it contains a valid TCP port, this port it used.
fixes #1420

mpsutil: http server takes port from property or env when in unit test

---

code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/run.mps

Hi,
Previously the expected version of cbmc was 5.3 or 5.4 or 5.5. Now I have changed the check to expect only 5.5 and the message conveyed also says 5.5.
I am not sure if mbeddr can support 5.3 and 5.4 also. This should not affect anything in mbeddr according to me.
Please review and merge in milestone/v15-3
Regards,
Dinesh

Changing the expected version of cbmc to 5.5

---

code/plugins/sl-all/solutions/de.itemis.mps.tooltips.runtime/models/de/itemis/mps/tooltips/runtime.mps

Hi,
When the tool tip component tries to paint the tooltip messages,  sometimes the editor component gets disposed and so the partially painted tooltip remains there in the implementation module and does not disappear until you restart the application. You can see it in the following images.
I am attaching the stack trace as text file here. 
[tooltip problem.txt](https://github.com/mbeddr/mbeddr.core/files/591273/tooltip.problem.txt)
In the below attached image, you could see that the stacktraces navigates me to the getMessage method of NodeHighlightManager where they have asserted whether the editor is disposed or not.
I have added a check to show the tooltip only if the editorcomponent is not disposed.
Please review and merge in milestone/v15-3
Regards,
Dinesh

Tool-tip populated in some cases looses contents and stays a ghost images- need to kill the application to remove these.

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

During a refactoring the evaluate method that doesn't need a ICoverageAnalyzer
was deleted from the interface causing a breaking change in the API. While
all known implementations of the interpreter still implement this method I
added back the method to the interface.

platform: Interpreter API compatibility

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

InterpreterBase was not passing a instance of NullCoverageAnalyzer but null
this cause the evaluators to throw NPEs.

platform: fix NPE caused by InterpreterBase

---

code/languages/com.mbeddr.debugger/languages/com.mbeddr.core.debug/languageModels/debugger.mps
code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.statemachines/generator/template/main@generator.mps

Problem Statement 1:
While debugging, the breakpoints support is not allowed for Epsilons Transactions & Junctions.
Solution & Fix 1:
The problem is because of the Trace-link(trace.info file) is missing for Epsilons Transactions & Junctions for state machine, hence fixing the defect by uncommenting the code which is avoiding trace linking of Epsilons Transactions & Junctions.
Problem Statement 2:
While debugging in many cases we are getting null pointer while resuming the debugging process.
Solution & Fix 2:
There is a null stack frame contributor for certain cases where it is including parent Implementation Module node into state frame, hence added a null check for stackFrameContributor in getContributorHierarchy() method of MFrameMapperImpl class to avoid null pointer exception.

Debugger defect fix for state machine junction

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/languageAccessories/com/mbeddr/core/unittest/messages.mps

Hi,
https://github.com/mbeddr/mbeddr.core/pull/1660/commits
In the previous commit i have changed the variable name of method(failed_range_double) in Unittest_helper which causes the value not being shown in the tool tip. So I have reverted the variable name. Also i have changed the range value data type to previously it was.
Please review the commit and merge it with milestone
Regards,

variable name changed causes value not showing in tooltip

---

code/applications/tutorial/solutions/com.mbeddr.tutorial.documentation/models/com/mbeddr/tutorial/documentation/ug/_main.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/typesystem.mps

-Fixed includable export generation in html
-Implemented a documentRefSection. This is not visible for the user we just need it during generation for building the table of contents and should be abandoned aftwerwards
-Document includes with reference only are generated down into includable exports
-DocumentRefSection generates a link to an external document in table of contents
-Implemented checking rule: document includes with reference only are valid only for documents contained in the same model

documentation:

---

code/languages/com.mbeddr.analyses/solutions/com.mbeddr.analyses.sat4j.fm/models/com/mbeddr/analyses/sat4j/fm/ui.mps

Hi,
After we apply the look and feel for model consistency, the column could not be expanded and content of the column header becomes unreadable.This is because when look and feel is applied, the width of the column is not enough for that particular font and other specifications.So i have increased the column width of first column in the table model consistency.Now the content of column header is shown and it is readable.Please review the changes and merge with milestone.

Column header of model consistency table is not shown properly and first column is unreadable.

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/editor.mps

Hi,
In the implementation module, on code-completion and type **exported** we have huge list of exported for various concepts. This is little bit confusing and since we have the exported from the base concept. I have removed those exported by changing the do-not substitute action of exported editor component.Please review the changes and merge it with milestone.
Regards,

Removing the export from implementation module on code-completion

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.expressions/languageModels/typesystem.mps

Hi ,
I have a controlled attribute which is being used in two places. When I change the type of the attribute variable its automatically updated in the other places. The updation takes place if the new type is a subtype of existing type. This doesnot handle case  where when we change double to double const or with annotated type since they are subtypes. So i have changed to check if it is the exact type by changing the check_ITyped_NameControlled constraint. Please review and merge the changes.
Example 1: 
Place1 :                           place2:
double a                        double ->a
**changing to double const**
Place1 :                           place2:
double const a               double ->a
Regards,

On using the controlled attribute the type is syncing only for subtypes.

---

code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/plugins/sl-all/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

The current implementation of diagram editor deletes the associated edges if we click and delete a box.

Ignore deleting the edges when we delete boxes in diagram editor

---

code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/generator/template/main@generator.mps
code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/languageModels/editor.mps
code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/languageModels/structure.mps
code/plugins/sl-all/diagram/languages/de.itemis.mps.editor.diagram/languageModels/typesystem.mps
code/plugins/sl-all/diagram/solutions/de.itemis.mps.editor.diagram.runtime/models/de/itemis/mps/editor/diagram/runtime/model.mps

This is an improvement to the earlier [pull request](https://github.com/mbeddr/mbeddr.core/pull/1777).
Earlier we stored the state as boolean field property in **Content_GenericBoxQuery** . But when we need different behaviors for the nodes of the same box query, we are unable to achieve it. So i have changed the boolean property as an optional Expression child(similar to the other children like allowScaling/allowConnections).

Improvement-Ignore deleting the edges when we delete boxes in diagram editor

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.projectview.runtime/models/com/mbeddr/mpsutil/projectview/runtime/tree.mps

It seems that the IViewDescriptor is already unregistered at that time.
Listeners are now initialized right before they are registered. If one
of them is configured to be disabled, it will never be initialized.
When removing the listener, we can just check if it is != null and don't
need the descriptor anymore.
Fixes #1822

ProjectView: NPE in CustomProjectView.removeListeners

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps

The looks up for that path difenetion didn't work correctly because it
was doing node comparison and they were from different (transient) models.
PathMapping lookup now done via name.

doc: fix absolut path generation

---

build/com.mbeddr/build.gradle
build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle

The logic inthe gradle scripts about dealing with the MPS path selector
was pretty distributed through multiple script files. Everything related
to the install tasked is now moved into the ":build:mbeddr.com" script.
Dependencies to the install tasked are then added dynamically.
Fixes #1837

build: Refactor install tasks and path selector

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps

Made `ListScope visibleContentsOfType(concept<> targetConcept)` virtual to allow
overwriting and also made the return type `Scope` instead of `ListScope`.
Deperecated the other methods in the API that take conceptNode paramters
and added overloads that use concep<> instead.
Changed the implementation of the conceptNode methods to call into the
new methods that use concept<>.
Reimplemented `findByName` with collection API rather than iterating the
sequence manually.
Added a comment explaning how a default implementation of `visibleContentsOfType(conceptNode<>)`
should look like given the fact that it is still abstract and needs to
be implemented but shouldn't duplicate the logic in `visibleContentsOfType(concept<>)`
Renamed the third overload that would return the `sequence` instead of the …

core: IVisibleElementsProvider migation preparation

---

build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle

By popular requests we are changing the default task to only build the platform. In order to inform the user about this change a banner is presented after the build if the user invoked the default task:
```
:build:com.mbeddr:platform:defaultWrapper
######################################################################################
######################################################################################
BUILD SUCCESSFUL
Total time: 11 mins 16.661 secs
```
Todo:

build: change the default task to build_platform

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.compare/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.compare/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.compare/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.compare/languageModels/typesystem.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/com/mbeddr/cimport/comparator/code/IgnoredReference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/com/mbeddr/cimport/comparator/code/MPSNodeComparator.mpsr

When using AssertNodeEquals (com.mbeddr.mpsutil.compare) for comparing two nodes, currently there is no provision to ignore certain references alone during comparisons. So i have introduced a class IgnoreReferece(similar to IgnoreProperty class which exists already) and used it in the generator of AssertNodeEquals and AreEqualExpression.

Ignoring certain references while using AssertNodeEquals for node comparisons

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/com.mbeddr.mpsutil.conceptdiagram.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/editor.mps

Making conceptsDiagram work again. Mostly getting rid of usages of old apis and cleaning up the code a bit.
Changes:
-removed usages of deprecated conceptnode and getConcept method from IConnectionEndPoint
-added extends dependency to jetbrains.mps.lang.structure
-cleaned up dead code
-replaced usages of removeWhere with where (could be a problem as removeWhere mutates the list)
-reloaded conceptdiagram dependencies

Fixing concepts diagram language:

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageModels/textGen.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps

Added a new annotation that allows handling conflicting generated document file names.
During generation one can use the annotation to make sure all names are unique, when copying the documents to doc_gen folder the facet makes sure that the names are again replaced with the original file name (as there we keep the folder structure from the node).
Downstream projects have to implement its own logic for attaching the annotation as per default the framework doesn't do it.

mbeddr.doc: TemporaryFileName annotation

---

build.gradle
build/com.mbeddr/build.gradle
build/publishing/build.gradle
build/thirdparty/build.gradle

As @eugenschindler reported in #1722 due to our build infrastructure changes, the build number was no longer part of the file name that was uploaded to github. 
The feature has been added again. You can have a look on a release here:
https://github.com/mbeddr/mbeddr.core/releases/tag/nightly-557

add MPS versions back to file names

---

build/com.mbeddr/languages/build.gradle

Somehow `install_actionsfilter`task was not included as dependency task to `install`.
Added back the dependency.

added install actions filter task as dependency to install task

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.xmlImport/models/plugin.mps

The xml importe action in mpsutil did not allow to select and import
multiple files. It's tedious to import a larger set of files. The
change to add this feature was pretty simple to implement by simply
itterating over multiple files.

mpsutil: allow multi xml file import

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps

Currently we will get a `ActionDuplicationException` when actions are removed from the profile and re-added to the **specify toobar** section. 
This commit just introduces an info that removing + re-adding the actions should not be done

Added comment next to the to the "specify toobar" section

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/base.mpl
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/structure.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/actions.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/constraints.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/intentions.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/migration.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/scripts.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps

Historically we had one big mpsutil plugin. Loading it was a all or nothing choice. I removed some of the bigger "subsystem" from the single plugin and created small plugins out of them. This allows fine grained loading in downstream projects. RCPs can easier decide which plugins they want to strip. 
It should also allow us an easier transition to mps-extenstion repo as we can move the plugins one by one. 
I also made sure that the big mpsutil plugin depends on the newly created ones. Downstream projects will not see any change until they decide to change their dependencies.

smaller plugins in mpsutil

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps

Had to delete the `paint` call as it requires the application which is always null during command line build.
This caused a null pointer exception in every screen shot and obviously no png was produced.

fix command line screen shooter execution

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.runconfiguration/solutions/pluginSolution/models/com/mbeddr/core/runconfiguration/pluginSolution/plugin.mps

Currently the _generate()_ method of class **GenerateModelsUtil** is not working for rebuilding of temporary models. So i have updated the methods to override the function  _**ModelsToResources.canGenerateCondition()**_ . Now this can rebuild temporary models in addition to the existing functionality. We can use the overridden method with corresponding condition for rebuilding temporary models.

Added method to override the canGenerateFunction of GenerateModelsUtil 

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.refactoring/generator/template/com/mbeddr/mpsutil/refactoring/generator/template/main@generator.mps

If a projection mode switcher with multiple options was used the emited
code wasn't correct. The generator used a `removeWhere` operation which
inconstrast to other operations on lists doesn't only add a filter but
mutates the list inplace. It was replaced with a normal `where` which
only acts as filter around the original list.
fixes #1876

mpsutil: fix projection mode switcher gen

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.ext.build/models/com/mbeddr/ext/build.mps
code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.components/languageModels/typesystem.mps
code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.compositecomponents/compositecomponents.mpl
code/languages/com.mbeddr.ext/languages/com.mbeddr.ext.compositecomponents/languageModels/typesystem.mps
code/languages/com.mbeddr.ext/tests/test.ex.ext.compositecomponents/compositecomponents.msd
code/languages/com.mbeddr.ext/tests/test.ex.ext.compositecomponents/models/basic@tests.mps

Following enhacements are made in this pull request:
- Improved checking rule for mandatory port in compoiste component to take into account delegations in addition to connections (an error is not reported anymore if the mandatory port is a delegation).
- Added a checking rule for adapter port to report an error when aan adapter on mandatory port is not used anywhere in the model.

Enhanced Mandatory port cheking rules 

---

code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/ui.mps
code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc/solutions/pluginSolution/models/com/mbeddr/analyses/cbmc/pluginSolution/plugin.mps

Hi All,
Added support for CBMC version 5.9 in CProverPreferenceUI(Spinner Box). I have made the following changes,
1. Changed the string usedCBMCVersion 5.8 to 5.9 in cproverpreferences.
2. Added another string 5.9 in usedCBMCVersionModel spinnerListModel in CproverPreferenceModel Class.
Please review the changes and merge to milestone/v17.0-1
Regards,

Support for CBMC version 5.9 in CProverPreferenceUI

---

code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/ui.mps
code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.utils/models/com/mbeddr/analyses/utils/results_ui.mps

Hi,
After we apply the look and feel for analyses tables (raw counter example and the results table), the column could not be expanded and content of the column header becomes unreadable.This is because when look and feel is applied, the width of the column is not enough for that particular font and other specifications.So i have added a method to set the max width with respect to table and font size .Now the content of column header is shown and it is readable.Please review the changes and merge with milestone.

Column header in analyses window is shrinked and is unreadable 

---

code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc/languageModels/behavior.mps
code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc/solutions/pluginSolution/models/com/mbeddr/analyses/cbmc/pluginSolution/plugin.mps

Hi,
We would like to execute some job before/after the "formal verification" is triggered/completed. The verification action always creates an object of "AnalysisConfigurationAnalyzerFactory" class which is responsible for collecting all analyses jobs and execute. The object creation can be delegated to the respective Analysis Configuration.  So created a virtual method in CProverBasedAnalysis behaviour and CBMCAnalysisConfigurationContainer behaviour. Changed the action to get the factory from the respective nodes. 
Regards,
Dinesh

delegating factory creation to corresponding analysis configuration node to do pre and post analyses jobs

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.spreferences.runtime/models/com/mbeddr/mpsutil/spreferences/runtime.mps

There is a solution spreferences which contains the configurations for a particular project such as platform templates, code review preferences etc  . Languages added to this solution are not of latest version . So migration window appears indicating migration has to done with this message ' Update Module in Descriptors ' . There is a class(Version Fixer) from MPS to update the language versions, used that language to update the language versions. Please review the changes and kindly merge with milestone .

Update versions of the languages added for the spreferences solution to avoid migration window popping up

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/intentions.mps

Hi All,
Right now the intention Use Controlled Name(makenamecontrolled) is directly available i.e the intention is applicable only if there any modules in the import section which implements the IControlledNameProvider. It is not available indirectly i.e if any of the module is reexporting the module which implements the IControlledNameProvider. So I have added logic in isApplicable condition of the intention to find the re-exported modules and check if any of them is an instance of IControlledNameProvider. 
Please review the changes and merge with milestone/v17.1-1
Kind Regards,

Making Use Controlled Name intention available for the reexported modules.

---

build.gradle

I am not sure if this is the optimal solution. However, should fix the problem that the artifacts built from maintenance version have the branch name as a  prefix. We need to fix this so that we can use the agreed "1.1.+" version specifier to get the latest platform.

build: fixed maintenance branch versioning

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.execution/models/com/mbeddr/mpsutil/editingGuide/execution.mps

- this was needed for the layouting information of the diagram framework to be carried into the editingGuide execution

…mpsutil.editingGuide.execution: copy code nodes of a task with preserved ids

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/solutions/pluginSolution/models/com/mbeddr/core/unittest/pluginSolution/plugin.mps

In future MPS releases this type inconsistency leads to generation failure instead of ClassCastException at run time

rewrite light quotation to avoid typesystem error

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps

IVisibleElementProvider.visibleContentsOfTypeAsSequences no longer raises NPE if .visibleContentsOfType returns null
- visibleContentsOfType sometimes returns a null scope
- In such case, visibleContentsOfTypeAsSequence currently throws an NPE
- let's return an empty sequence instead to make it more consistent and fix the following background issue
- aNode.visibleContentsOfType(…).getAvailableElements(null) is commonly used.
- Let's allow refactoring such occasions into aNode.visibleContentsOfTypeAsSequence(…) to replace the NPE with an empty set of elements
- this case is tough to debug since mixing behavior and baseLanguage methods, while the first do raise NPE and the second don't raise NPEs when calling them on null objects
- the setting in which this exception was triggered from …

NPE in IVisibleElementProvider.visibleContentsOfTypeAsSequence

---

build.gradle

- used to be fixed 1.0-SNAPSHOT
- log the built version
That would be consistent with iets3.core then: https://github.com/IETS3/iets3.core/blob/master/build.gradle#L42
Does anyone have local automation that could break with it?

Local builds are now $major.$minor-SNAPSHOT

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.querylist.demolang/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editor.querylist.runtime/models/com/mbeddr/mpsutil/editor/querylist/runtime.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editor.querylist.sandbox/models/com/mbeddr/mpsutil/editor/querylist/sandbox.mps

Given I have a node which shows querylists as well as RefNodeLists
When I focus a constant cell outside these lists
And I hit RETURN
Then the next upcoming RefNodeList will receive an INSERT action with a null anchorNode
But unexpectedly, QueryLists will not be considered
See how it jumps over the QueryList:
- the reason seems to be that QueryLists return `null` when calling their `getSRole()`
- `ChildrenCollectionFinder#find` seeks for the next cell with `EditorCell#getSRole().isMultiple() == true`
- `EditorActionUtils#callAction` uses it to find the corresponding action and run it
- I made the `EditorCell_QueryList` set a dummy `SAbstractLink` as SRole of itself which always returns `true` on calls to`isMultiple()`. The other methods return some null objects.
- Then I needed to fix …

c.m.m.e.QueryList: catch INSERT in front of a QueryList

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/generator/template/main@generator.mps

Building an interpreter for a concept which has a backslash character in its alias will lead to a Java compile error. This is because the backslash will be part of a string in the generated code and will be interpreted as an invalid escape character. This PR fixes this by duplicating each backslash in the corresponding Java string.

Fix Java compile problem in Interpreter generator

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.ecore.ui.modelexporter/com.mbeddr.mpsutil.ecore.ui.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.ecore.ui.modelexporter/models/com/mbeddr/mpsutil/ecore/ui/plugin.mps

To fix the mentioned problems in #2058  I've refactored the ui-action related part of the `com.mbeddr.mpsutil.ecore.ui` plugin. 
**The major changes**
* deprecated oudated API
* unified all JChooser in single place: `EcoreImporterUI`
* AWT events now executed outside command
* wrapped relevant code parts in commands

mpsutil.ecore.ui: refactored ui-actions

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

added 
```
boolean containsValueInCurrent(Object object); 
Object getInCurrent(Object object); 
boolean containsKeyInCurrent(Object object);
```
to IEnvironment and implemented them in `EnvironmentImpl`

Interpreter: added possibility to query an env without consulting the parent env

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.textGen.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.json.sandbox/models/com.mbeddr.mpsutil.json.sandbox.model.mps

This PR includes couple of minor improvements in the text gen and editors of json language:
- arrays: allow empty arrays and print brackets on single line for empty arrays
- objects: print parenthesis for empty objects on single line
- variables: add space after colon in text gen
- arrays/objects: set focus between the brackets/parenthesis on creation
- strings: allow empty strings in the editor

Improve json text gen and editors

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.spreferences/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.spreferences.runtime/models/com/mbeddr/mpsutil/spreferences/runtime.mps

Hello All,
https://github.com/mbeddr/mbeddr.core/pull/1982
As part of the above issue, version fixer is added to SPreferenceUtil class to avoid the migration pop-up dialog. But due to recent migration to MPS 2018.3 the code has been commented as there was a minor change in the function signature of VersionFixer constructor. So I have uncommented the code and changed the constructor to take the project as an argument from the PreferencePageDescription root template.
Please review the changes and merge them with milestone/v19.2_20183.
Kind Regards,

Restored VersionFixer in SPreferenceUtil class to avoid migration pop-up window dialog

---

build/thirdparty/jdk/build.gradle

The latest jdk version available in nexus is: 8u152b1136.39 which was required for MPS 2018.3.
This PR increases the version to 8u202b1483.21.

build:thirdparty: updated jdk version according to mps 2019.1

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.spreferences.runtime/models/com/mbeddr/mpsutil/spreferences/runtime.mps

Null pointer exception comes from the 'SetPathToGeneratedArtifactsToReviewAction' on right clicking the model inside the spreferences solution.In the 'isApplicable' method of the action ,output path of the model is checked ,which causes the null pointer exception.This is because the generator output path of the solution is not set while creating the solution.
I have set the generator path of the solution pointing to the source gen folder.Hence the exception doesn't come on right click. Fix is identical to the MPS java class 'NewModuleUtil' in which the generator path of the solution descriptor is set in the same way.
Kindly review the changes and merge with milestone.
Regards ,
Vignesh M

 Null pointer exception on right clicking the model inside Spreferences and type size configuration solution 

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/models/behavior.mps

In the 'getPrefix()' method of the macro folder and file picker behaviour, getValue() method is called to evaluate and get the value of the macro.When the macro is null the function getValue() throws argument cannot be null exception.
Added a null check so that it calls the method getValue() only when the macro is not null.
Kindly review the changes and merge with milestone.
Regards ,
Vignesh M

Illegal argument exception pops up during code completion of macro folder and file picker

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.nodeaccess/models/com/mbeddr/mpsutil/nodeaccess/plugin.mps

The field MPSInternalPortManager.PORT has long been deprecated
and is removed in 2020.1.
getCurrentPort() is to be used instead.

Replace deprecated static field reference with a static method.

---

code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.requirements/languageModels/editor.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/editor.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps

The breadcrumb runtime is diabled for a long time, it makes no sense
to have the breadcrumb editor cells around and to generated code into
the editors for breadcrumb handling. It seems like this code is also
creating problems when documentation language is in presentation mode
since it tries to attach selection listeners twice.

doc, core, cc: remove breadcrumb from editor

---

code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps

A `ConcurrentModificationException` is thrown when multiple editor components are disposed (for example, when `Close All` menu is invoked or when project is closed).

Fix ConcurrentModificationException in Documentation Plugin occurring on multiple editor components disposal

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.smodule/languageModels/typesystem.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.smodule.runtime/com.mbeddr.mpsutil.smodule.runtime.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.smodule.runtime/models/com/mbeddr/mpsutil/smodule/runtime/lib.mps

Because now GlobalModelAccess has no way to execute a command, we have to provide a project repository to the add model operation.
For now I made the repository optional so that we just don't break the existing usages. When a repository is not provided we try to get it from the opened projects.

mpstutil.smodule: fixed GlobalModelAccess usage in addModelOperation

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com/mbeddr/mpsutil/common/graph.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com/mbeddr/mpsutil/common/graphTest@tests.mps

When copying a `Graph<T>` with its `copy()` method, the original and the copied graph were not independent. E.g., when removing an edge in one of the two graphs, the edge also vanished in the other one. Expected behavior: Each of the graphs (the original and the copy) can be changed independently.
This PR fixes this odd behavior and also contains two testcases.

Bugfix for Graph.copy(), it doesn't create a proper independent copy.

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps

The concept `ModelContentAsImageParagraph` from mbeddr.doc allows to embed model nodes (by reference) in documentation. A caption/description can be added to the model content. However, in presentation mode this description is not displayed, but a generic text like `Code from ...`. 
This PR ensures that the actual description is shown instead of the generic text (if in presentation mode). 
Note: In the old implementation, Ctrl-Click on the description text jumped to the embedded model node. I couldn't do this; so now the figure number is a navigatable node. If the reviewer has a hint how to make the description navigatable again, please comment.

Change caption text of a model-as-image in presentation mode.

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/com.mbeddr.doc.aspect.ui.msd
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps

The issue this PR is fixing: TabbedDocViewer fails to render its content if a concept has two or more conditional editors.

Fix-up for conditional editors in TabbedDocViewer

---

README.md

- I wrote down what I identified as needed steps to contribute to mpsutils throughout interviewing @slisson and @coolya 
- didn't find a good naming convention for solutions that demo the results of a sandbox language, best hit: mylanguage.sandbox.sandbox (since it is the sandbox for the sandbox language…)
- maybe it would make sense to leave out the detail steps on build script and test script, since they'll outdate quickly. On the other hand, having such would be a great help to get it right even if not entirely correct anymore.
- maybe we can build a checklist out of that as default PR content?

 Added "Contributing to the mbeddr.platform" to README

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.refactoring/generator/template/com/mbeddr/mpsutil/refactoring/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.refactoring/languageModels/behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.refactoring/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.refactoring/languageModels/structure.mps

This PR enables the possibility to define custom code for [PushHintOption](http://127.0.0.1:63320/node?ref=1fc20ffe-f35b-4791-a0b7-d706bad5c49a%2Fr%3A18d75373-a465-46d0-9749-aacc22a947bc%28com.mbeddr.mpsutil.refactoring%2Fcom.mbeddr.mpsutil.refactoring.structure%29%2F3897771026684496949&project=com.mbeddr.mpsutil) which ends up in the genrerated java code. 
A PushHintOption contains now an optional  child of type [PushHintFunction](http://127.0.0.1:63320/node?ref=1fc20ffe-f35b-4791-a0b7-d706bad5c49a%2Fr%3A18d75373-a465-46d0-9749-aacc22a947bc%28com.mbeddr.mpsutil.refactoring%2Fcom.mbeddr.mpsutil.refactoring.structure%29%2F7849801688419935966&project=com.mbeddr.mpsutil) with some predefined arguments. 
see:
This allows the user of the language to integrate his own custom code in the …

PushHintOption can contain custom java code

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/pluginSolution.msd
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/com.mbeddr.doc.test.documents.msd
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/doc1.mps

Screenshots didn't respect the content removal specified in the
ModelContentAsScreenShotParagraph since we migrated to the logic
that takes screenshots from the intermediate model and not from
the original model.
This changes sets the editors hints for the intermediate model
correctly in the docs languages to allow the remove to work.
Only setting the hints wasn't enough because conditional editors
were disabled in the screenshooter code since the editor hints
for conditional editors were not set. The screenshooter now
always sets the conditional editor hint so that conditional
@slisson can you let me know if [setting](http://127.0.0.1:63320/node?ref=r%3A0a882e21-5553-485b-8777-3b0ace5a0d84%28com.mbeddr.core.base.pluginSolution.plugin%29%2F1344466372819333811) both conditional editor …

doc: fix code removal in screenshots

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/pluginSolution.msd
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/com.mbeddr.doc.test.documents.msd
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/doc1.mps

This PR backports #2162 to MPS 2020.1
Screenshots didn't respect the content removal specified in the
ModelContentAsScreenShotParagraph since we migrated to the logic
that takes screenshots from the intermediate model and not from
the original model.
This changes sets the editors hints for the intermediate model
correctly in the docs languages to allow the remove to work.
Only setting the hints wasn't enough because conditional editors
were disabled in the screenshooter code since the editor hints
for conditional editors were not set. The screenshooter now
always sets the conditional editor hint so that conditional

[2020.1 backport] doc: fix code removal in screenshots

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageModels/plugin.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.transitiveIncludes.mps

Remove the limitation that a document could only get included once. It
is now possible to include a document in as many places as desired. The
resolving of transient imports is supported and includes are resolved in
inverse topological order (from the leaf to the root). The generator
automatically restores references within the including document to
content that is included if required.
The reference resolving logic is limited to resolve references to
included content only to the first include. This means including the
same document twice in one document will not yield the desired result.
Please see the code comments for much more details on the design.

doc: add support for multiple doc includes

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.structure.mps

The previous implementation enforces that a JsonFile contains a JsonObject as the root node of the contained JSON text.
This is not in accordance with the JSON Standard, which allows _any_ JSON value (such as arrays or a numbers in addition to objects) to be the root of a JSON text.
Refer to [https://www.ecma-international.org/publications-and-standards/standards/ecma-404/](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/), Section 4.
Since a JSON object is a JSON value, this change does not break existing models.

Permit any JSON value as root of a JsonFile instead of only JSON Objects

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

Premature use of ActionsFilter during startup causes an "IDE Fatal Error"
```
Should be called at least in the state COMPONENTS_LOADED, the current state is: CONFIGURATION_STORE_INITIALIZED
Current violators count: 1
java.lang.Throwable
at com.intellij.diagnostic.LoadingState.logStateError(LoadingState.java:63)
at com.intellij.diagnostic.LoadingState.checkOccurred(LoadingState.java:59)
at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.<init>(ActionManagerImpl.java:169)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessor …
```

mpsutil: fix ActionsFilter IDE error

---

build.gradle
build/com.mbeddr/build.gradle
build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle

The build now publishes the master and maintenance/* branches to github
packages in addition to the normal itemis maven repository. The changes
are backwards compatible and don't require any changes on teamcity,
apart from providing the github logins data.
Read the inline comments carefully because some changes are none obvious
without. Mostly caused by the fact that we configure our subproject from
a parent project was tricky to get right.

build: additional publishing to github packages

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/code.mps

Currently NodeAttributes are not shown in model nodes which are added to mbeddr.doc documentation using the "embed model content as image" mechanism. This is due to the querylist flag `duplicates safe` being set to true in the two editors of the corresponding concept.
This PR sets the flag `duplicates safe` to false, leading to NodeAttributes becoming visible again.
Remark: Due to @slisson, problems may occur if the same node is being projected by querylist twice in the same editor and edited. In the current implementation, this may happen if the user creates two "embed model content as image" paragraphs for the same model node (or for a node and additionally for one of its descendants). However, I think this is unlikely in documentation. 
@joao-silveira We could also set the querylist in …

Show NodeAttributes in "embed model as image" paragraphs in mbeddr.doc

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps

Copy images for configs located in a different solution than the export configuration.

doc.gen: fix in images export

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.preferenceform.runtime/models/AbstractPreferenceFormConfigurable.mpsr

When opening preferences, the following error message appears:
`java.lang.ClassNotFoundException: com/mbeddr/mpsutil/breadcrumb/runtime/plugin/BreadcrumbPreferences_Configurable`
This commit removes the offending line in AbstractPreferenceFormConfigurable.
The error happens because in Intellij the class [EpBasedConfigurableGroup](https://github.com/JetBrains/intellij-community/blob/0e2aa4030ee763c9b0c828f0b5119f4cdcc66f35/platform/platform-impl/src/com/intellij/openapi/options/ex/EpBasedConfigurableGroup.kt#L133) tries to load the class AbstractPreferenceFormConfigurable but fails. If anyone knows more about this, you can suggest a better
solution than commenting out the line that doesn't work.

Fix ClassNotfoundException in preference components

---

build.gradle
build/com.mbeddr/build.gradle
build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle

Applies identical changes as in PR #2180 to the MPS20203 maintenance branch so that this older version is also published to github packages.
See also: 2c585c7c815884659d360a548df9edea8dd5db67

build: additional publishing to github packages (maintenance/MPS20203)

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps

Due to problems with stable-id computations (see issue #2191), duplicate stable-ids have been generated for different link targets. This is solved by this PR. Additionally, image file names could be not unique if two or more `ModelContentAsImageParagraph` nodes have the same name (issue #2190). This is also fixed by this PR.
This PR closes #2190 and #2191.

mbeddr.doc: Fix ToC link clashes and image file name clashes

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps

In presentation mode, a table-of-contents in an mbeddr.doc document is just a constant string "table of contents". With this PR, it is an actual table of contents list, with clickable links.
Example ([node URL](http://127.0.0.1:63320/node?ref=r%3Ae178f830-5ea3-43a6-9d0d-4469b64bfbe8%28com.mbeddr.doc.markdown.sandbox.doc2markdown%29%2F603951059624405033)):
This closes issue #2187.

mbeddr.doc: Show ToC in presentation mode

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/languageAccessories/com/mbeddr/doc/gen_xhtml/defaults.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/typesystem.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/com.mbeddr.doc.test.documents.msd
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.chapter_refs.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.doc_refs.mps

It is possible to reference documents from different models in two
different ways:
* Using a document include checking the "reference only" box
This will contribute an entry to the table of contents that links to
the referenced document
* Using a doc ref word
This will generate a "word" link to the referenced document. Nothing is
added to the table of contents.

doc.gen: allow referencing documents from different models

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules.gen/generator/template/com/mbeddr/core/modules/gen/generator/main/util.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/generator/template/com.mbeddr.core.modules.generator.com.mbeddr.core.modules.util.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/generator/template/main@generator.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/modules.mpl
code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/generator/template/main@generator.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/generator/template/main@generator.mps

As part of profiling efforts in a customer projects we identified a couple of hotspots during generation. 
Most of them were typesystem related. To cache the expensive typesystem calls I introduced `TypeCacheHelper` which essentially applies memoization. It is used to wrap all call to the typesystem and will return a result from it's cache when it encounters the same node twice. 
The new typesystem cache is used in:
- `handleArrayStructUnionInitExprAndAssignments`
- `TransparentStructHelper`
From my testing caching there doesn't break anything but please do some extensive testing in other codebases to see if this really holds. 
The second hotspot we identified was sorting the module content. Here as well we apply caching. Since the sortied relies on function signatures the function to a …

Generator performance

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.build/models/com/mbeddr/build/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules.gen/generator/template/com/mbeddr/core/modules/gen/generator/main/util.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/generator/template/com.mbeddr.core.modules.generator.com.mbeddr.core.modules.util.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/generator/template/main@generator.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/languageModels/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.modules/modules.mpl
code/languages/com.mbeddr.core/languages/com.mbeddr.core.unittest/generator/template/main@generator.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.util/generator/template/main@generator.mps

As part of profiling efforts in a customer projects we identified a couple of hotspots during generation.
Most of them were typesystem related. To cache the expensive typesystem calls I introduced TypeCacheHelper which essentially applies memoization. It is used to wrap all call to the typesystem and will return a result from it's cache when it encounters the same node twice.
The new typesystem cache is used in:
handleArrayStructUnionInitExprAndAssignments
TransparentStructHelper
From my testing caching there doesn't break anything but please do some extensive testing in other codebases to see if this really holds.
The second hotspot we identified was sorting the module content. Here as well we apply caching. Since the sortied relies on function signatures the function to a given …

Generator performance (#2200)

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/com.mbeddr.mpsutil.actionsfilter.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps

This PR removes the dependency to `de.itemis.mps.editor.bool` and therefore the Widgets plugin and its dependency don't have to be installed anymore when installing the actionsfilter idea plugin.

Actionsfilter: Remove dependency to mps-extensions

---

code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage.extended/models/documentation.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/com.mbeddr.doc.aspect.exampleLanguage.mpl
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/models/com/mbeddr/doc/aspect/exampleLanguage/documentation.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/models/com/mbeddr/doc/aspect/exampleLanguage/editor.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/models/com/mbeddr/doc/aspect/exampleLanguage/structure.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/sandbox/com.mbeddr.doc.aspect.exampleLanguage.sandbox.msd
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/sandbox/models/com/mbeddr/doc/aspect/exampleLanguage/sandbox.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/generator/template/main@generator.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/editor.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect/models/com/mbeddr/doc/aspect/structure.mps
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/com.mbeddr.doc.aspect.runtime.msd
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/models/com/mbeddr/doc/aspect/runtime.mps
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.ui/models/com/mbeddr/doc/aspect/ui/plugin.mps

This PR adds support for setting priorities for the annotations of the  documentation aspect. Now it is possible to document concepts of other languages in the documentation aspect as well. The annotation with the highest priority is used when there are multiple available documentations for a concept.

Document aspect: add priorities 

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.generatorfacade/models/com/mbeddr/mpsutil/generatorfacade/runtime.mps

The `GeneratorFacade` class does not support changing generator options. E.g., for debugging it is sometimes needed to set `saveTransientModels` to `true`.
The changes in this PR extend the API to allow providing a specific set of generator options. In addition, a new API method `defaultOptionsBuilder` provides an `OptionsBuilder` which can be used and adapted.
The changes are backwards compatible.
Usage example:

Allow using GeneratorFacade with more flexible options

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

the same versioning number is now used as for all the other plugins

mbeddr.core.build: add version number to mpsutil.uisupport

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/com.mbeddr.mpsutil.actionsfilter.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

This PR fixes https://github.com/mbeddr/mbeddr.core/issues/2199. Action profiles that are active by default now have an additional condition to decide if they should be activated.
That means that you can have multiple profiles that are active by default but have different activation conditions:
This setting doesn't affect manually activated profiles through the preference page because the  condition isn't (and also can't be) persisted in the user settings.
NOTE: This is a breaking change (generator) and therefore existing action profiles need to be regenerated.

ActionsFilter: add an activation condition

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps

Previously the links were only generated for the TOC and the section in the documentation itself was just skipped.

Doc xhtml: generate links to referenced documents

---

build/com.mbeddr.allScripts/build.xml
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/modules.xml
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/com.mbeddr.mpsutil.editor.displayControl.sandbox.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.constraints.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.listeners.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.typesystem.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/sandbox/com.mbeddr.mpsutil.editor.displayControl.sandbox.sandbox.msd
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/sandbox/models/com.mbeddr.mpsutil.editor.displayControl.sandbox.sandbox.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/com.mbeddr.mpsutil.editor.displayControl.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/generator/templates/com.mbeddr.mpsutil.editor.displayControl.generator.templates@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/models/com.mbeddr.mpsutil.editor.displayControl.behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/models/com.mbeddr.mpsutil.editor.displayControl.constraints.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/models/com.mbeddr.mpsutil.editor.displayControl.editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/models/com.mbeddr.mpsutil.editor.displayControl.structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl/models/com.mbeddr.mpsutil.editor.displayControl.typesystem.mps

Contribution:
Provide an interface that allows for a user to hide a node in the editor, but the logic for hiding it is delegated to client code.
The interface name is ICanHide and is located in org.iets3.core.base.
It provides 3 methods:
boolean isVisible(), used to query the intended visibility state
void hide(), used to indicate the node should be hidden
void show(), to indicate the node should be shown
The boolean state is temporarily saved in a userObject, thus it is not persisted within the model.
The handling of user object is closed to the provided methods so that no additional string objects are created.
This PR closes #2244

#2244 Interface to hide arbitrary nodes in the editor.

---

code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.plantuml/solutions/pluginSolution/models/com/mbeddr/mpsutil/plantuml/pluginSolution/plugin.mps

The caption of the Copy Sources action in the Plantuml Viewer was wrong. It was "Zoom in" and should be "Copy sources to clipboard". Action can be found [here](http://127.0.0.1:63320/node?ref=c0488c1e-322f-4f38-92d4-5520a7ce96c1%2Fr%3Ae053bdde[…]sutil.plantuml.pluginSolution.plugin%29%2F7754683290286257299](http://127.0.0.1:63320/node?ref=c0488c1e-322f-4f38-92d4-5520a7ce96c1%2Fr%3Ae053bdde-b82f-4d5b-a735-e0af382d4ef2%28com.mbeddr.mpsutil.plantuml.pluginSolution%2Fcom.mbeddr.mpsutil.plantuml.pluginSolution.plugin%29%2F7754683290286257299 ) 
This PR fixed it.

mpsutil: changed caption for CopySource action

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

A selected profile was not saved when restarting MPS. The profiles are now correctly saved in the [configuration directory](https://www.jetbrains.com/help/mps/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#config-directory). This functionality was completely broken before.

Actionsfilter: fix saving of profiles

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_latex/generator/template/com/mbeddr/doc/gen_latex/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/doc.mpl
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/migration.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.editor.displayControl.sandbox/sandbox/com.mbeddr.mpsutil.editor.displayControl.sandbox.sandbox.msd
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.graphstream.example/sandbox/com.mbeddr.mpsutil.graphstream.example.sandbox.msd
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.incrementalcomputation.example/sandbox/com.mbeddr.mpsutil.incrementalcomputation.example.sandbox.msd
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.lantest.assertions/com.mbeddr.mpsutil.lantest.assertions.mpl
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.smodule.runtime/com.mbeddr.mpsutil.smodule.runtime.msd

ModuleIdentity is a deprecated concept and shouldn't be used anymore. It also produces a warning when writing the documentation. A migration is provided to automatically switch to the new concept.

Documentation: replace ModuleIdentity with ModulePointer in ModuleRefWord

---

CHANGELOG.md
code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.cbmc.rt/models/com/mbeddr/analyses/cbmc/rt/ui.mps
code/languages/com.mbeddr.analyses/languages/com.mbeddr.analyses.utils/models/com/mbeddr/analyses/utils/results_ui.mps

The original exception was:` java.lang.IllegalArgumentException: column must be valid`.It happened constantly in the CBMC lifted results tool. I've also updated the fonts to make the text more readable.

Analyses: fix fonts and exception in results table

---

CHANGELOG.md
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps

The `CRHelperCell` should include both the grow-y and push-y style, the same way the lines cells in the celllayout language do. Otherwise, such interesting issues can occur:
The `CRHelperCell` somehow makes the calculation of the last row's width wrong, and therefore the border of the last row is also drawn wrong (too long). With this fix, the calculation is done correctly.

Core base: add missing push-y style in CRHelperCell

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/modules.xml
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/com.mbeddr.mpsutil.json.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/plugin.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.xmlImport/models/plugin.mps
code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/models/tests.com.mbeddr.mpsutil.json.tests@tests.mps
code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/tests.com.mbeddr.mpsutil.json.msd

This PR picked up already existing work from the branch _feature/json_importer_ and finalizes it. The behaviour of the paste and import actions is similar to the one provided by for the `xml` laguage.
Inside an **empty JSON document** or inside an **JSON object**,  users can paste valid and parsable JSON object text-snippets.
In addtition to the paste we also allow imports of **multiple JSON files**. Therefore a model action is provided allowing the users to select multiple json files for import.

mpsutil.json: added paste and import action

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.conceptdiagram/languageModels/editor.mps

These diagrams are often not layouted, let's just run the layouter when they are opened the first time.

mpsutil.conceptdiagram: run autolayout on init

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/editor.mps

On Windows, the path uses by default a `\` instead of the `/` used by MacOS/Linux. The Windows platform Java can handle the forward slash at runtime. This commit ensures that only forward slashes are used in file paths.

Canonicalize paths in the resource editor

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

Includes #2316 (to avoid conflict in the changelog), please review that one first.
Passing `null` as action ID to IDEA's `CustomActionsSchema#addIconCustomization()` causes it to break later when persisting the settings. This didn't happen on 2021.3 so the fix is only needed for 2022.2 onwards.

Fix 'error when saving settings' caused by actionsfilter plugin

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps

CellScreenshooter now throws an error when it cannot generate a screenshot and we hit that exception when trying to generate screenshots from an Ant build. Instead of throwing an error, skip generating the screenshot and output a warning to point the user to a solution. Make sure to output the warning at most once per facet invocation, and only if there are screenshots.

Do not generate screenshots from MpsEnvironment, output a warning

---

.github/workflows/PR-into-next-version.yml

When a maintenance branch pushed, create a PR to merge changes into the next version.

Create a PR to merge a maintenance branch into the next one on push

---

.github/workflows/PR-into-next-version.yml

Update merge branch from base branch (i.e. merge `maintenance/mps[NEXT]` into `merge/mps[PREV]`) because the PR rules in this repo require this.

Automerge: update merge branch from base branch

---

CHANGELOG.md
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/typesystem.mps

Automatically remove assessment result entries with invalid references e.g. a node or concept was removed. The automatic resolving of those references will fail and can completely lock up the editor if there are a lot of references.

Delete invalid assessment result entries

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

The main motivation was to make the API easier and add support for disabling the computation trace.

Interpreter: generalize the evaluate methods into one method with options

---

build.gradle
build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle
build/thirdparty/graphviz/build.gradle

Scanning projects for secure bill of materials (SBOM) is faciliated by the providing SPDX compliant
license, organization and source code information.
The modification on the build scripts enhance the created `pom.xml` by the information.
The users of the platform will benefit from the additional information by using automated processes that analyze the `pom.xml` in their projects.

#2349 add a spdx compliant license, organization and scm information to the created pom of published mbeddr artifacts

---

CHANGELOG.md
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.doc/models/main.mps

- The cell editor screenshooter doesn't trim the offset of the editor component anymore.
- The escaping of the new line character works again in the HTML generator.
- The cell editor screenshooter now supports editor extensions and the rendering quality was slightly improved.	
Unfortunately, I couldn't figure out why the quality of the generated png files is still worse than in the editor. There is no compression going on, all rendering hints are set and the size of the generated image also looks right to me.

Small documentation language improvements

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

A dummy computation trace is now used when the computation trace is not available in the interpreter to prevent NullPointerExceptions. This can happen when the interpreter is called with tracing disabled and the `trace` expression is used.

mpsutil.interpreter: Add a dummy computation trace when the computation trace is not available

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/typesystem.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

This is necessary in case multiple conflicting profiles could be enabled (e.g. through a dependency).

Add priorities for action profiles which can be enabled by default

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.filepicker/models/behavior.mps

We need this also in MPS 2021.3 so that the cascading merged don't overwrite the version.

Backport PlantUML EPL version

---

.gitignore
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_markdown/generator/templates/com.mbeddr.doc.gen_markdown.generator.templates@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.plantuml.node/com.mbeddr.mpsutil.plantuml.node.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.plantuml.node/languageModels/behavior.mps

That dep. is not used and not needed and is causing dep. errors when those languages are packaged as part of an RCP.

markdown/plantuml: removed not needed dep. to mpsutil.httpsupport 

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/generator/template/com/mbeddr/doc/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps

This fixes the warning: `SModelRepository.getModelDescriptor(String) is ineffective, please refactor to use SModelReference` for the documentation language.

doc.generator: fix deprecation warning

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.logicalChild/models/com.mbeddr.mpsutil.logicalChild.behavior.mps

The previous implementation of method `ILogicalChildOwner.getModelsWithLogicalChildren()` does not work if the ILogicalChildOwner and ILogicalChild nodes reside in a transient model. This PR makes the implementation more robust. 
The change is not visible to platform users. At the moment, it is only relevant for variability filtering as part of a generator step.
Closes #2408.

Fix ILogicalChildOwner behavior for execution in transient models

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/modules.xml
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/com.mbeddr.mpsutil.common.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com.mbeddr.mpsutil.common.util@tests.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com/mbeddr/mpsutil/common/model.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.common/models/com/mbeddr/mpsutil/common/util.mps
code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.common/models/test.com.mbeddr.mpsutil.common.util@tests.mps
code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.common/test.com.mbeddr.mpsutil.common.msd

This PR provides two helper classes implementing the `Supplier<T>` interface. They can be used for lazy evaluation as well as lazy evaluation with an expensive and a cheap computation part. 
The PR also provides tests for these helper classes.
I also added existing tests for `c.m.mpsutil.compare` to the CI testing job, as I believe the tests are useful and should be executed on CI (boy scout's rule).
The change is not visible to users, so no CHANGELOG entry.
Solves #2424.

Add two memoizing supplier implementations

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/comparator.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/.model
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/AttributeDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/ChildDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/DiffView.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/DifferentConceptDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/DifferentNumberOfAttributesDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/DifferentNumberOfChildrenDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/IgnoredProperty.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/IgnoredReference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/MPSComparatorOptions.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/MPSNodeComparator.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/MissingReferenceDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/MpsNodeComparatorOptionsBuilder.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/NodeDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/PropertyDifference.mpsr
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator/models/ReferenceDifference.mpsr

In addition to some null checks, node annotations and children of references can now be compared. The node difference descriptions were also improved. Also fixes #2308 but there is no separate error message because I couldn't reproduce the issue that I reported myself.

mpsutil.comparator: small improvements

---

build/com.mbeddr/languages/build.gradle

Useful for pull requests where we want to build everything to check.
Applies #2464 to maintenance/mps20222 branch.

Add the ability to force platform build

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/modules.xml
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.checkinHandler.demo.plugin/com.mbeddr.mpsutil.checkinHandler.demo.plugin.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.checkinHandler.demo.plugin/models/com.mbeddr.mpsutil.checkinHandler.demo.plugin.plugin.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.checkinHandler.demo/models/com.mbeddr.mpsutil.checkinHandler.demo.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.checkinHandler/com.mbeddr.mpsutil.checkinHandler.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.checkinHandler/models/com.mbeddr.mpsutil.checkinHandler.plugin.mps

Create a new extension for CheckinExtensionPoint to add a new handler. You can find some example handlers in `com.mbeddr.mpsutil.checkinHandler.demo.plugin`. The handlers can accept a commit, reject it or execute arbitrary actions.

mpsutils: create a new language for check-in handlers

---

subprojects/com.mbeddr/build.gradle

Due to some inexplicable Gradle behavior (probably a bug), when `maven-publish` plugin is applied to `com.mbeddr` project, it causes the subproject configuration in `subprojects` block to misbehave. Instead of adding a repository to each subproject, the repository is added multiple times to the parent.
Removing the `plugins` block from `com.mbeddr` fixes this.
Since `com.mbeddr:distribution` does not apply these plugins, publishing repositories are now configured only when the `maven-publish` plugin is applied.

Fix broken build

---

subprojects/com.mbeddr/languages/build.gradle
subprojects/com.mbeddr/platform/build.gradle

Dependency on `copy_allScripts` must now be added explicitly to the mbeddr C build.

Fix CI build

---

build/com.mbeddr/analyses.test/build.gradle
build/com.mbeddr/distribution/build.gradle
build/com.mbeddr/everythingElse/build.gradle
build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle
build/publishing/build.gradle
settings.gradle.kts

Part of #2500 applied to the 2022.2 branch to fix the CI build.

Strip `:build` prefix from project names

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/com.mbeddr.mpsutil.hyperlink.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/languageModels/plugin.mps

The update from MPS 2022.2 to MPS 2022.3 broke the language by removing an internal field of the editor component. This PR fixes it.

mpsutil.hyperlink: use own copy of ReferenceUnderliner

---

build/com.mbeddr/languages/build.gradle

The dependency was transitive via the spawner before but has to be added directly now.

build_mbeddr: add dependency on copy_allScripts

---

build/com.mbeddr/build.gradle

The tasks are no-op in 2022.2 but are executed on CI for every pull request. Proper implementation will be added in maintenance/mps20223 and above.

Add migration tasks

---

build.gradle
code/languages/com.mbeddr.build/.mps/libraries.xml
code/languages/com.mbeddr.build/.mps/vcs.xml
code/languages/com.mbeddr.build/solutions/com.mbeddr.core.tests.build/models/com/mbeddr/core/tests/build/build.mps
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/libraries.xml
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.demo.comparator.diff/com.mbeddr.demo.comparator.diff.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.asynccell.sandbox/models/behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.asynccell.sandbox/models/editor.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/com.mbeddr.mpsutil.actionsfilter.runtime.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator.diff.demo.genplan/com.mbeddr.mpsutil.comparator.diff.demo.genplan.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.comparator.diff.demo.tests/com.mbeddr.mpsutil.comparator.diff.demo.tests.msd
code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.common/test.com.mbeddr.mpsutil.common.msd
code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.ecore.metaModelImport/models/test/com/mbeddr/mpsutil/ecoreimporter/testFailDifferentPropertyName.mps
subprojects/com.mbeddr/build.gradle
subprojects/com.mbeddr/platform/build.gradle

New migration tasks, only migrating com.mbeddr.mpsutil and com.mbeddr.build for now, with more projects to follow.
Since migration will fail if an non-built language is encountered in a project, a new build script was added (sandboxes) to build all languages that were not built by other build scripts.

`migrate` and `remigrate` tasks

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/pluginSolution.msd
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps

The access was changed to command because the auto-layouter of the diagrams language needs command access and not only read acess to the model.

core.base: autolayout diagrams before taking a screenshot

---

build.gradle
build/com.mbeddr/build.gradle

We use the downloaded JBR to run Ant.

build: Remove unused jdk_home variable

---

code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps

Otherwise, the created word steals the focus, and it is also not necessary to have a blank word at the beginning of the paragraph.

mbeddr.doc: clear created words in initialized TextParagraph

---

build/com.mbeddr/languages/build.gradle
build/com.mbeddr/platform/build.gradle

The Gradle convention (as implemented by the built-in [`lifecycle-base` and `base` plugins](https://docs.gradle.org/current/userguide/base_plugin.html)) is to have a `build` task which runs `assemble` and `check`, where `assemble` builds the package and `check` runs tests (by depending on a `test` task) or any further checks such as linting, or in our case potentially model checks.
This PR implements this convention. As a prerequisite, it also decouples `package_*` tasks from `test_*` tasks so that tests only run when explicitly requested.
It should now be possible to simply run `build` or `check` to build and test the whole project.

build: Use Gradle lifecycle tasks

---

build/com.mbeddr/languages/build.gradle

Because we always need the platform zip unzipped.
In case of a local build we zip the platform first and then unzip it again later, but we keep the projects more independent, and we can fix this later with more Gradle modelling.

build: depend on resolve_mbeddr_platform

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.doc.aspect/languages/com.mbeddr.doc.aspect.exampleLanguage/models/com/mbeddr/doc/aspect/exampleLanguage/structure.mps
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/com.mbeddr.doc.aspect.runtime.msd
code/languages/com.mbeddr.doc.aspect/solutions/com.mbeddr.doc.aspect.runtime/models/com/mbeddr/doc/aspect/runtime.mps

This is an attempt to fix https://youtrack.jetbrains.com/issue/MPS-37663/Failed-to-instantiate-aspect-interface-jetbrains.mps.smodel.runtime.StructureAspectDescriptor-in-language-my.language.

doc.aspect.runtime: depend on a IntelliJ platform library for the cache instead of de.q60.mps.collections.libs

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/.mps/modules.xml
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/com.mbeddr.mpsutil.collections.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/generator/templates/com.mbeddr.mpsutil.collections.generator.templates@generator.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/models/com.mbeddr.mpsutil.collections.behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/models/com.mbeddr.mpsutil.collections.constraints.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/models/com.mbeddr.mpsutil.collections.editor.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/models/com.mbeddr.mpsutil.collections.structure.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.collections/models/com.mbeddr.mpsutil.collections.typesystem.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.collections.runtime/com.mbeddr.mpsutil.collections.runtime.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.collections.runtime/models/com.mbeddr.mpsutil.collections.runtime.mps
code/languages/com.mbeddr.mpsutil/solutions/test.com.mbeddr.mpsutil.collections.runtime/models/test.com.mbeddr.mpsutil.collections.runtime.mps
code/languages/com.mbeddr.mpsutil/solutions/test.com.mbeddr.mpsutil.collections.runtime/test.com.mbeddr.mpsutil.collections.runtime.msd

A new language `com.mbeddr.mpsutil.collections` was added that adds support for a set type `nset` that use nodes as the values of the set. Equivalence of nodes is checked structurally. The hash code calculation is done for all properties and children and the first level of references. The runtime solution also contains a more general class `EquivalenceHashSet` to implement hash sets with arbitrary `equals` and `hashcode` methods. `nset<>` is also compatible with `set<node>` and can be used as its type instead.
Implementation note: I didn't use the built-in implementation like the matches statement and the StructuralNodeSet from MPS because it deals poorly with copied nodes. For example, a copy of a class sometimes is not structural equal to the class itself: …

mbeddr.mpsutil: add a new language com.mbeddr.mpsutil.collections that provides an nset type

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.compare/languageModels/typesystem.mps

We've got a lot of errors like
```
[launchtests] [ 195231] SEVERE - jetbrains.mps.newTypesystem.context.ReportingTypecheckingContext - Typing equation did not provide node to report. Error will be ignored. Equation 3942143736278655464 from model r:f7b641c7-0327-4513-80ee-fa0921b93a79(com.mbeddr.mpsutil.compare.typesystem)
```
This PR fixes them by assigning a proper node to all typesystem checks in `com.mbeddr.mpsutil.compare`.

make sure all typechecks in mpsutil.compare have a node to report

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.allScripts/models/com/mbeddr/allScripts/build.mps
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.preferenceform/com.mbeddr.mpsutil.preferenceform.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.preferenceform/generator/template/main@generator.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.preferenceform.runtime/models/AbstractPreferenceFormConfigurable.mpsr

Prevent message when pressing Ctrl-Shift-A: "No display name specified in plugin descriptor XML file for configurable XXX; specify it using 'displayName' or 'key' attribute to avoid necessity to load the configurable class when Settings dialog is opened"
Happened for every PreferenceForm

Fix exception on FindAction-action

---

code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps

Without it, line wrapping doesn't work properly.

Use indent layout for element documentation

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.generatorfacade/com.mbeddr.mpsutil.generatorfacade.msd
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.generatorfacade/models/com/mbeddr/mpsutil/generatorfacade/runtime.mps

Use RegularPlanBuilder instead of RigidPlanBuilder in [GeneratorFacade](http://127.0.0.1:63320/node?ref=r%3A00bd75cf-1225-4ef5-9a7e-390aed8718dd%28com.mbeddr.mpsutil.generatorfacade.runtime%29%2F5915735921188775088) to properly support enhanced Transform generation plan steps with multiple Transform.entries that should be executed in one single step (RigidPlanBuilder doesn't support this). Previously multiple languages specified in the Transform.languages were always combined in one generation step.

genfacade: use RegularPlanBuilder instead of RigidPlanBuilder

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

WeakReference is killed any time the garbage collector runs, whereas SoftReference is killed only if memory is low.
Should lead to more cached interpreters.

use SoftMap instead of WeakMap to cache interpreters

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps
code/languages/com.mbeddr.cc/languages/com.mbeddr.cc.requirements/languageModels/behavior.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.arrays/languageModels/behavior.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/base.mpl
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/behavior.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/languageModels/editor.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/languages/com.mbeddr.core/languages/com.mbeddr.core.base/solutions/pluginSolution/pluginSolution.msd
code/languages/com.mbeddr.core/languages/com.mbeddr.core.statements/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.spreadsheat/spreadsheat.mpl

- fixes https://github.com/mbeddr/mbeddr.core/issues/1967
The mbeddr search tool was improved: It can now also search the project and globally. It also got options for approximate searching with an error distance, and matching the case. The UI was also improved:

Improvements to mbeddr search tool

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.interpreter/runtime/models/com/mbeddr/mpsutil/interpreter/rt.mps

@enikao FYI: We got the error message `com.intellij.util.IncorrectOperationException: containsKey() makes no sense for weak/soft map because GC can clear the value any moment now `

mpsutil.collections: don't use containsKey with the soft value map

---

CHANGELOG.md
code/languages/com.mbeddr.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/com.mbeddr.mpsutil.json.mpl
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.behavior.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/com.mbeddr.mpsutil.json.textGen.mps
code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.json/models/plugin.mps
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.json.sandbox/models/com.mbeddr.mpsutil.json.sandbox.model.mps
code/languages/com.mbeddr.mpsutil/tests/test.com.mbeddr.mpsutil.ecore.metaModelImport/test.com.mbeddr.mpsutil.ecore.metaModelImport.msd
code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/models/tests.com.mbeddr.mpsutil.json.plugin.mps
code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/models/tests.com.mbeddr.mpsutil.json.tests@tests.mps
code/languages/com.mbeddr.mpsutil/tests/tests.com.mbeddr.mpsutil.json/tests.com.mbeddr.mpsutil.json.msd

The text generator output of `com.mbeddr.mpsutil.json` was improved and the escaping of special characters was implemented. The output options and JSON parsing can now also be configured through the extension point `json` in the method JsonConfig#getFactory. For more information read: https://github.com/fasterxml/jackson-core/wiki/JsonFactory-Features, https://github.com/fasterxml/jackson-core/wiki/JsonGenerator-Features and https://github.com/fasterxml/jackson-core/wiki/JsonParser-Features.
The PR is breaking since escaping characters can only be disabled for non-ASCII characters (through JsonGenerator.Feature.ESCAPE_NON_ASCII) and not for the quotation character which would produce an invalid JSON file. In case there is another change regarding the output, it should be possible to …

[breaking] mpsutil.json: improve exporting of files and make parser and export options customizable through an extension point

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

This solves issue #2670.
Currently, the `com.mbeddr.platform` build script specifies a folder `icons` for the plugin `com.mbeddr.mpsutils`. This folder collects all contents from various `icons` folders in the project. However, it also listed the full directory `$mpsutils/solutions`, which leads to lot of stuff being contained in the deployed `com.mbeddr.platform` artifact. This also leads to some errors and warnings in the logs when MPS is running. 
This PR replaces the item `$mpsutils/solutions` by all folders below this directory named `icons` (which are actually only two). I also checked for files below this folder with extensions `*.png` and `*.svg`, but did not find other icon files outside of the two sub-folders I added.
Risk: There might be files in the packaged folder …

Ensure that packaged artifact does not contain unwanted solutions

---

.gitignore
subprojects/com.mbeddr/build.gradle
subprojects/com.mbeddr/platform/build.gradle

* Use a configuration for MPS home. A Gradle configuration is a better abstraction for the location of MPS
than a task whose type changes depending on some condition.
* Change MPS extraction directory to `build/mps` to avoid polluting the project directory. Since `resolve_mps` is now a `Sync` rather than `Copy`, there is no risk of accidentally using an incorrect MPS version.

build: fix building with custom MPS (JetBrains Teamcity)

---

code/languages/com.mbeddr.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

MPS does not remove them when reloading modules from disk (MPS-38285) and we have accumulated quite a few over the years. If not removed, they may contribute to module loading errors in MPS 2024.1.

Remove obsolete runtime solutions from the build

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps

* MakeScreenshotRunnable does not need to hold on to its image result.
* Catch all Throwables while running in order to also catch OutOfMemoryErrors.

bugfix(doc): improve memory usage of generateScreenshots facet

---

.github/renovate.json5

* Enable MPS and MPS-extensions updates on maintenance/mps2024x branches.
* Enable only patch updates of MPS and libraries.
* Configure 'loose' versioning for MPS extensions to ignore 'a'/'b' letters in commit hashes. The default Gradle versioning would treat them as prereleases and Renovate would skip them (on maintenance branches).
* Automerge Renovate PRs on Wednesday mornings.

Renovate configuration updates

---

.github/renovate.json5

Also fix the regex of maintenance branches to ignore branches created by renovate (`renovate/maintenance/...`)

renovate: disable JBR updates on maintenance branches

---

.github/renovate.json5

Loose versioning does not support version ranges and it led to unwanted updates on maintenance branches.

renovate: switch from loose versioning back to allowing unstable

---

code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

Exclude sbom.json from mps-extensions when creating platform distribution content (to avoid collision with platform's own sbom during final platform zip packaging).

Exclude SBOM from mps-extensions

---

code/languages/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.extensionclass/languageModels/constraints.mps

There's no need to use long-time deprecated utility method to access a property.
The method has been removed in MPS master (upcoming 25.1 release)

Inline SNodeUtil.getResolveInfo()

---

code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

MPS is now strict about missing plugin dependencis (MPS-38286) 
pluginSolution requires j.m.ide.editor which comes from "workbench" plugin.

Plugin mpsutil.jung depends on "full" MPS (aka workbench)

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

If we do not do this outside of the EDT thread, the class will complain because it can't be initialized on this thread when we need it for the ActionsApplicationComponent.
Another similar issue in MPS: https://youtrack.jetbrains.com/issue/MPS-33812/Assertion-failed
This exception is very unlikely to happen anyway because MPS probably also needs to initialize this class somewhere.
https://github.com/mbeddr/mbeddr.core/issues/2340 is not reproducible (happens very rarely) for me but should be fixed by that.

mpsutil.actionsfilter: initialize the action manager before working with it

---

build.gradle
code/languages/com.mbeddr.build/solutions/com.mbeddr.ext.build/models/com/mbeddr/ext/build.mps
code/languages/com.mbeddr.ext/tests/test.ts.ext.components.embedded/models/main@tests.mps
code/languages/com.mbeddr.ext/tests/test.ts.ext.components.embedded/tests.ts.ext.components.embedded.msd

Add a build configuration to ensure that test classes are not dropped.

Fix test.ts.ext.components.embedded to work with 2025.1

---

.github/renovate.json5

The version of PlantUML to use will be changed in the 2024.1 branch and cascaded to master, but Renovate configuration has to be applied to master.
PlantUML versioning scheme changed from versions like 8059 to versions like 2017.x and then again to 1.2017.x, and we want only these 1.x.y versions.

renovate: do not upgrade PlantUML to old versions

---

subprojects/com.mbeddr/platform/build.gradle

8059 is an old version, update to this version will be blocked by #2950.

Upgrade plantuml to 1.2025.2

---

gradle/libs.versions.toml

Use JBR version from the final MPS 2025.1 release.

updated JBR version for 2025.1 release

---

code/languages/com.mbeddr.doc/solutions/com.mbeddr.spreadsheet.libs/com.mbeddr.spreadsheet.libs.msd

It's stub-only solution.
Empty root yields annoying "Models have not been found within the SourceRoot..." warning in build log.

spreadsheet.libs module doesn't need empty models/ root

---

CHANGELOG.md
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_latex/generator/template/com/mbeddr/doc/gen_latex/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_markdown/generator/templates/com.mbeddr.doc.gen_markdown.generator.templates@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/com.mbeddr.doc.gen_xhtml.mpl
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc.gen_xhtml/generator/template/com/mbeddr/doc/gen_xhtml/generator/template/main@generator.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/behavior.mps
code/languages/com.mbeddr.doc/languages/com.mbeddr.doc/languageModels/plugin.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.markdown.sandbox/models/com.mbeddr.doc.markdown.sandbox.doc2markdown.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/com.mbeddr.doc.test.documents.msd
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.doc_refs.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.tests@tests.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/com.mbeddr.doc.test.documents.transitiveIncludes.mps
code/languages/com.mbeddr.doc/solutions/com.mbeddr.doc.test.documents/models/doc2_1.mps
code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform.tests.build/models/com.mbeddr.platform.tests.build.mps
code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

This PR addresses https://github.com/mbeddr/mbeddr.core/issues/2958 and uses original node IDs for generating SIDs (stable IDs) where possible. 
In addition some rudimental tests were added to check for generation of stable IDs.
**Explanations**
Previously, only node.StableID() was utilized. By default, the behavior method is applied to the node within the generator model (transient). The node ID is updated every time because the generator always creates a copy of all nodes and transfers them to the transient model.
To obtain **real** stable IDs, we need to use the IDs from the original model. However, in some cases, a node may not have been present in the original model because it was previously transformed or created in another generator. Initially, I did not include an “instance of” …

mbeddr.doc: make IDs robust over several generations

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
code/languages/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

The previous fix from May 2025 (merged from 2023.2) introduced a different problem due to changed threading rules in 2024.1: "PluginException: Access from Event Dispatch Thread (EDT) is not allowed; see https://jb.gg/ij-platform-threading for details". This is now fixed by disabling actionsfilter updates until startup is complete.

Fix actionsfilter initialization

---

CHANGELOG.md
code/languages/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

This was only done when opening the preference component in the past.

mpsutil.actionsfilter: load the default profile on startup

---

CHANGELOG.md
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.ideaplugin/com.mbeddr.mpsutil.actionsfilter.ideaplugin.msd
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/com.mbeddr.mpsutil.actionsfilter.runtime.msd
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps
code/platform/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

* Put the actionsfilter runtime and ideaplugin solutions under the lib/ folder in the plugin to make them accessible by IDEA. Fixes "com.intellij.diagnostic.PluginException: Cannot create extension (class=com.mbeddr.mpsutil.actionsfilter.ideaplugin.EnableActionFilterUpdates)".
* Change these solutions to use the provided (IDEA) classloader. Fixes ClassCastException due to classes being loaded by separate classloaders.

fix: actionsfilter classloading issues

---

CHANGELOG.md
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.actionsfilter/languageModels/editor.mps
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.contextactions/models/editor.mps
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.actionsfilter.runtime/models/com/mbeddr/mpsutil/actionsfilter/runtime.mps

Call `getChildActionsOrStubs()` instead, if the group is a `DefaultActionGroup`. Fall back to `ActionGroup#getChildren()` otherwise. In this case IDEA should not complain.
The "or stubs" part should be okay because all MPS actions will be fully loaded fully anyway and we do not call the actions themselves. We do compare the instances in a few places and if we find that this causes problems we should switch to comparing IDs instead.
The PR also includes a related refactoring to use `ActionManager` instead of `ActionManagerEx` and `getActionIdList()` instead of the deprecated `getActionIds()`.
Fixes #3071.

Fix calls to ActionGroup#getChildren

---

CHANGELOG.md
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.core.base/models/behavior.mps
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink.sandbox/models/editor.mps
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/com.mbeddr.mpsutil.hyperlink.mpl
code/platform/com.mbeddr.mpsutil/languages/com.mbeddr.mpsutil.hyperlink/languageModels/plugin.mps
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.core.base.pluginSolution/models/com/mbeddr/core/base/pluginSolution/plugin.mps
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.editingGuide.execution/models/com/mbeddr/mpsutil/editingGuide/execution.mps
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.nodeaccess/models/com/mbeddr/mpsutil/nodeaccess/plugin.mps
code/platform/com.mbeddr.mpsutil/solutions/com.mbeddr.mpsutil.traceExplorer/models/com.mbeddr.mpsutil.traceExplorer.plugin.mps
code/platform/com.mbeddr.platform.build/solutions/com.mbeddr.platform/models/com/mbeddr/platform/build.mps

Migrate all usages of NavigationSupport to EditorNavigator (and one
usage to ProjectNavigator which is a similar helper class for locating
the node in the logical view).
NavigationSupport was often being used from a write lock, in 2025.1 this
leads to a deadlock. EditorNavigator presents a better API: it can be
called without holding a read/write lock and it accepts node references
instead of nodes.
Testing:
- hyperlink: open DummyConcept node in the
com.mbeddr.mpsutil.hyperlink.sandbox.sandbox.manualTest model, click
on 'A URL link to another node', MPS should not freeze.
Fixes #3175, fixes #3180.

Fix navigation support deadlocks

---

CHANGELOG.md
code/platform/build.gradle

These are the libraries that are bunded with MPS-extensions, and therefore with mbeddr platform too.

build(platform): add provided dependencies of mpsLibraries to the POM
